### ISSUE TITLE
Start command

### ISSUE THREAD

**Issue by dennis-carlson1995** [stackblitz/webcontainer-core#724] opened 2022-06-20 17:13 UTC
### Describe the bug

Start command won't run 

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts

### Steps to reproduce

Attempt to run the sample project 
Receive "failed to run start command" 

### Expected behavior

For the start command to run and the preview to be visible 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 102.0.5005.115
Major version = 102
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64210030,
  "usedJSHeapSize": 57077770,
  "jsHeapSizeLimit": 2172649472
}
Hash = bbb482e7415e406cfc62838751ca694c1dc24cf6
```

**Comment by fvsch** [comment] 2022-06-20 20:06
Hi @dennis-carlson1995.

To be able to investigate your issue, we'll need a project URL that shows the issue.

The URL you shared is a short-lived URL that we can't look at. Some documentation sites that use the StackBlitz SDK generate this kind of short-live projects, but unless you click the “Fork” button to save it under your account and give it a permanent URL we won't be able to look at it.

Alternatively you can provide some steps to reproduce, such as “(1) Go to this documentation page, (2) click the 'Open in StackBlitz' button, (3) wait for dependencies to install, (4) wait for start command to fail”.

**Comment by aakash14goplani** [comment] 2022-06-21 05:10
I am facing same issue. This is happening with the Stackblitz that have Terminals. I am trying to run code linked from official Angular documentation. Here is one such [example](https://stackblitz.com/edit/angular-rddocp?file=src%2Fapp%2Fhost-parent%2Fhost-parent.component.ts,src%2Fapp%2Fself-no-data%2Fself-no-data.component.ts), as said one such meaning none of them are working for me at the moment. I started noticing this since 06/18/2022.  

**Attaching few screenshot for reference purpose:**
![image](https://user-images.githubusercontent.com/13452115/174719527-cf442114-b1e2-4b6a-a890-a4436f832f85.png)

**Picture from console:**
![image](https://user-images.githubusercontent.com/13452115/174720643-3199e514-e18f-434c-a70c-e18a93d196b2.png)

**Some more debug info:**
```
Browser name  = Chrome
Full version  = 102.0.0.0
Major version = 102
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 143667665,
  "usedJSHeapSize": 125879085,
  "jsHeapSizeLimit": 2172649472
}
Hash = bbb482e7415e406cfc62838751ca694c1dc24cf6
```

Hope this helps!

**Comment by tobychidi** [comment] 2022-06-21 07:08
Same issue here

**Comment by SamVerschueren** [comment] 2022-06-21 12:54
Hi everyone!

The problem you all are experiencing are timeouts on our side. We're actively working on resolving this issue but can't give you an estimate yet. Keep you posted 🙏 .

**Comment by SamVerschueren** [comment] 2022-06-30 08:42
An update has been deployed and the `npm install` process should be faster now. I'll close this issue for now, but feel free to create a new one if you still run into projects which experience this same issue. Hopefully this is a thing from the past now 🙏 .

**Closed by SamVerschueren** 2022-06-30 08:42 UTC
Labels: needs more info
