### ISSUE TITLE
nestjs start:dev

### ISSUE THREAD

**Issue by ghalibansari** [stackblitz/webcontainer-core#596] opened 2022-02-15 18:13 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/20482230/154123231-c0234d0c-79f9-4985-8c6a-d85c2a709c29.png)

### Link to the blitz that caused the error

https://stackblitz.com/edit/nestjs-typescript-starter-dpcg5d?file=package.json&terminal=start

### Steps to reproduce

use nestjs project and try to run 
npm run start:dev

### Expected behavior

its should run fine

### Parity with Local

- [x] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 99.100.4844.27
Major version = 99
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.100.4844.27 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 114458062,
  "usedJSHeapSize": 108098950,
  "jsHeapSizeLimit": 4294705152
}
Hash = e1937cc6e2ee7e7a1da198d43493f4063378a564
```

**Comment by jrvidal** [comment] 2022-02-15 22:15
Duplicate of https://github.com/stackblitz/webcontainer-core/issues/391

**Closed by jrvidal** 2022-02-15 22:15 UTC
