### ISSUE TITLE
File upload crashes dev server in certain cases

### ISSUE THREAD

**Issue by ciscoheat** [stackblitz/webcontainer-core#1323] opened 2024-02-13 10:18 UTC
### Describe the bug

When uploading a file and the validation for it fails, the dev server crashes.

### Link to the blitz that caused the error

https://stackblitz.com/edit/superforms-2-file-uploads-hzk8fj?file=src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2Fschema.ts,src%2Froutes%2F%2Bpage.server.ts

### Steps to reproduce

1. Upload an image smaller than 50 kB
2. "Form posted successfully!" is displayed in the browser, with file information in the terminal
3. Upload an image larger than 50 kB
4. File information is displayed in the terminal, but then it crashes.

### Expected behavior

No crash and an error message should be displayed for the file in the browser.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="976" alt="2024-02-13 11_14_06-" src="https://github.com/stackblitz/webcontainer-core/assets/130450/1b9596ce-0f72-43e3-8db1-e742ce4e0aaa">

### Platform

- OS: Win 10
- Browser: Chrome
- Version: 121.0.6167.161

### Additional context

Error logs when crashing:

```
Error: `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (/home/projects/superforms-2-file-uploads-hzk8fj/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:10341:19)
    at eval (/home/projects/superforms-2-file-uploads-hzk8fj/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50714:25)
    at eval (/home/projects/superforms-2-file-uploads-hzk8fj/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50705:21)
    at ssrRewriteStacktrace (/home/projects/superforms-2-file-uploads-hzk8fj/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50704:10)
    at ssrFixStacktrace (/home/projects/superforms-2-file-uploads-hzk8fj/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50757:24)
    at Object.ssrFixStacktrace (/home/projects/superforms-2-file-uploads-hzk8fj/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:60441:13)
    at fix_stack_trace (/home/projects/superforms-2-file-uploads-hzk8fj/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:271:8)
    at eval (/home/projects/superforms-2-file-uploads-hzk8fj/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:539:13)
```

**Comment by SamVerschueren** [comment] 2024-02-15 07:41
Closing this as a duplicate of #1240

**Closed by SamVerschueren** 2024-02-15 07:41 UTC
Labels: duplicate, tracked
