### ISSUE TITLE
Can't start Angular Starter project

### ISSUE THREAD

**Issue by IgorArnaut** [stackblitz/webcontainer-core#1055] opened 2023-05-01 21:42 UTC
### Describe the bug

I was following Angular Getting Started tutorial. I generated a sample project and installed dependencies. But for some reason, the project couldn't start after `ng serve` at all. Here is the error:

```
$ ng serve
Unknown error: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/projects/m7nmdq/node_modules/cliui/node_modules/string-width/index.js from /home/projects/m7nmdq/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /home/projects/m7nmdq/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.

~/projects/m7nmdq 56s
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/m7nmdq?file=src%2Fmain.ts

### Steps to reproduce

1. Generate a ready-made Angular sample project
2. Log in
3. Fork the generated project
4. Install dependencies
5. Start with 'ng serve'
6. Error

### Expected behavior

The project should just start.

### Parity with Local

- [ ] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/57326929/235536367-4c8a50a8-72ea-476e-979f-1d59a8a36d3a.png)

### Platform

- OS: Windows 10 64-bit
- Browser: Firefox
- Version: 112.02

**Comment by SamVerschueren** [comment] 2023-05-02 10:10
Can you try this again? It seems to work on my end 🤔 .

**Comment by jrvidal** [comment] 2023-05-03 10:37
I can reproduce, thanks for reporting.

**Comment by jrvidal** [comment] 2023-05-03 10:45
This seems to be an artifact of our NPM replacement, `turbo`.

We are actually planning on releasing an unmodified version of the NPM package manager in the near future, and that should solve this issue.

We're now tracking this internally, we'll update it accordingly.

Thanks for the report again!

**Comment by jrvidal** [comment] 2023-05-10 08:10
I'm closing this as a duplicate of https://github.com/stackblitz/webcontainer-core/issues/1070, you can track progress there!

**Closed by jrvidal** 2023-05-10 08:10 UTC
Labels: bug, tracked
