### ISSUE TITLE
BUG: npx didn't execute as expected in bash

### ISSUE THREAD

**Issue by tamsamani** [stackblitz/webcontainer-core#156] opened 2021-06-05 10:20 UTC
**Describe the bug:**
the command `npx tailwindcss init -p` fails in level of turbo and didn't generate the expected files.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/app-creator?file=package.json

**Steps to reproduce:**

1. install Dependencies `yarn add tailwindcss@latest postcss@latest autoprefixer@latest -D`
2. run `npx tailwindcss init -p`
3. See error related to turbo

**Expected behavior:**
generate two files as expected are  `tailwind.config.js` and `postcss.config.js`  in root of the project.

**Version of webcontainer:**
Hash: cb1eb6b301af424e8dffb694972509f06ea6b5db

**Screenshots:**
![image](https://user-images.githubusercontent.com/6149387/120888342-bafe0f80-c5ef-11eb-8701-1de2b2a7087d.png)

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.37
performance.memory = {
  "totalJSHeapSize": 104987385,
  "usedJSHeapSize": 101068613,
  "jsHeapSizeLimit": 4294705152
}

**Additional context:**
I use **Stackblitz** IDE after install it from browser(edge chromium) to use it a separate window, no dev plugin installed

**Comment by tamsamani** [comment] 2021-06-05 10:27
May be related in the same problem/issue

- directly: #129 
- non directly: #133 , #134 ,

**Comment by SamVerschueren** [comment] 2021-06-05 11:43
Thanks for reporting @tamsamani 🙏 ! Closing because it's a duplicate of #129.

**Closed by SamVerschueren** 2021-06-05 11:43 UTC

**Comment by SamVerschueren** [comment] 2021-06-05 11:45
You can also run the binary directly without `npx`, then it does seem to work. But it should work with `npx` as well.

```
$ tailwindcss init -p
```
