### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by haiderali1966** [stackblitz/webcontainer-core#601] opened 2022-02-21 12:21 UTC
### Describe the bug

 ng generate component product-alerts
An unhandled exception occurred: Cannot set property global of #<Object> which has only a getter
See "/tmp/ng-zVFV1C/angular-errors.log" for further details.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-3var1u?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html

### Steps to reproduce

2

### Expected behavior

gave error when i was going to generate a component product-alerts 

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 98.0.4758.102
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 101948782,
  "usedJSHeapSize": 93893550,
  "jsHeapSizeLimit": 2172649472
}
Hash = d64d45524a435df425e7813603b52872ecfbe08e
```

**Comment by soumi67** [comment] 2022-02-21 16:47
same here I dont know why Im having this bug

**Comment by haiderali1966** [comment] 2022-02-21 22:01
Thnx for responding on my thread/bug. Due the bug i could not work further
on stackblitz/webcontainer-core and had to be stopped.

**Comment by soumi67** [comment] 2022-02-22 13:54
well I skipped this step and I am now using vs editor

**Comment by jrvidal** [comment] 2022-02-22 15:16
Duplicate of https://github.com/stackblitz/webcontainer-core/issues/604

**Closed by jrvidal** 2022-02-22 15:16 UTC
