### ISSUE TITLE
Error: Buffer is not defined

### ISSUE THREAD

**Issue by davidstevenrojas** [stackblitz/webcontainer-core#431] opened 2021-11-25 18:30 UTC
### Describe the bug

After creating a NodeJS project, try to connect to Github as a new private repository, enter a name and click create repo and push, the Error: Buffer is not defined pops up, the repo is created in Git but it does not push its contents: 

https://www.screencast.com/t/k2rd8mHyolDl

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-q8cb9b

### Steps to reproduce

- Click on new Node.js blank project

- Once the workspace loads, click on Connect repository

- Enter a name, make it a private repo and click Create and Push

### Expected behavior

The repo should be created and pushed to Github completely without issues

### Screenshots

![image](https://user-images.githubusercontent.com/1041144/143488254-86812d45-e2ca-45af-a7ad-f359a57f0627.png)
![image](https://user-images.githubusercontent.com/1041144/143488287-6ccc662f-d76b-4cc4-809d-d193fac7f74c.png)
![image](https://user-images.githubusercontent.com/1041144/143488312-021a4877-ea57-457e-9951-c1a6f29b1a5a.png)

### Platform

```
Browser name  = Chrome 
Full version  = 97.0.4681.0
Major version = 97
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4681.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 77005951,
  "usedJSHeapSize": 70911239,
  "jsHeapSizeLimit": 2172649472
}
Hash = f0f0e35d34e6f38828752db79b041c48b98806b5
```

**Comment by tony19** [comment] 2021-11-30 23:37
Looks like the issue is no longer reproducible (perhaps fixed already)

**Comment by davidstevenrojas** [comment] 2021-12-01 01:10
I confirm this is not happening to me anymore.

**Comment by jrvidal** [comment] 2021-12-01 10:37
:tada: We shipped a fix for this recently, glad that it's gone.

**Closed by jrvidal** 2021-12-01 10:37 UTC
Labels: git
