### ISSUE TITLE
StackBlitz server crashed

### ISSUE THREAD

**Issue by amaljacksman** [stackblitz/webcontainer-core#1475] opened 2024-06-28 16:49 UTC
### Describe the bug

crashed on load

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/amaljacksman/excel-to-formarray

### Steps to reproduce

just start the app

### Expected behavior

To up the APP

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = 499be3932f50ab06349575b1c9042f95bc072a8b
WebContainer = 70dbe416

Browser name  = Chrome
Full version  = 100.0.4896.88
Major version = 100
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 81676894,
  "usedJSHeapSize": 69579318,
  "jsHeapSizeLimit": 2172649472
}
```

### Additional context

TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at registerModule (https://exceltoformarray-g5ef.w-credentialless-staticblitz.com/builtins.5bf3667c.js:161:1216)
    at registerImportModuleDynamically (https://exceltoformarray-g5ef.w-credentialless-staticblitz.com/builtins.5bf3667c.js:266:529)
    at internalCompileFunction (https://exceltoformarray-g5ef.w-credentialless-staticblitz.com/builtins.5bf3667c.js:266:1091)
    at wrapSafe (https://exceltoformarray-g5ef.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:13497)
    at Module._compile (https://exceltoformarray-g5ef.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:13881)
    at Object.Module._extensions..js (https://exceltoformarray-g5ef.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:14855)
    at Module.load (https://exceltoformarray-g5ef.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:12820)
    at Function.Module._load (https://exceltoformarray-g5ef.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:10273)
    at Function.executeUserEntryPoint [as runMain] (https://exceltoformarray-g5ef.w-credentialless-staticblitz.com/builtins.5bf3667c.js:165:1641)

Node.js 18.20.3

**Comment by SamVerschueren** [comment] 2024-08-07 10:39
Duplicate of https://github.com/stackblitz/webcontainer-core/issues/1492

This is now resolved.

**Closed by SamVerschueren** 2024-08-07 10:39 UTC
Labels: tracked
