### ISSUE TITLE
Git 

### ISSUE THREAD

**Issue by gyansatapathy** [stackblitz/webcontainer-core#444] opened 2021-11-29 05:50 UTC
### Describe the bug

after creating new repository from the stackblitz this error can be seen.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-2dttn2?file=bestSum.js

### Steps to reproduce

in the project, 
click on connect repository.
it creates new repository but unable to push the code into it and keeps on loading.

### Expected behavior

should be able to push the code.

### Screenshots

![image](https://user-images.githubusercontent.com/27923338/143815413-2328bb71-19b1-4586-92aa-9f499a2c2cd6.png)

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 94762484,
  "usedJSHeapSize": 77072552,
  "jsHeapSizeLimit": 4294705152
}
Hash = f0f0e35d34e6f38828752db79b041c48b98806b5
```

**Comment by tony19** [comment] 2021-11-29 15:34
Duplicate of #431

**Comment by jrvidal** [comment] 2022-01-20 22:47
@gyansatapathy #431 was fixed, so I'm closing this. Please feel free to open a new issue if you still see something breaking.

**Closed by jrvidal** 2022-01-20 22:47 UTC
