### ISSUE TITLE
Navigation bar not updating

### ISSUE THREAD

**Issue by yashdesoi** [stackblitz/webcontainer-core#223] opened 2021-07-01 15:42 UTC
**Describe the bug:**
After navigating to a particular route by clicking an an attribute element, the navigation bar doesn't update. For example if I click `<a href="/sample-route">Click</a>` in HTML the navigation bar must show abc.com/sample-route but rather it remains the same as original (Before navigation) abc.com

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-demo-app?file=index.js

**Steps to reproduce:**

1. Go to Above provided link of my stackblitz project
2. Type node index.js in the terminal
3. Let the project load, after the loading is complete click **Next** button in preview screen. 
4. Observe the navigation bar it remains the same as **node-demo-app--3000.local.webcontainer.io** instead of **node-demo-app--3000.local.webcontainer.io/new**

**Expected behavior:**
After clicking the **Next** button, navigation bar must show **node-demo-app--3000.local.webcontainer.io/new**

**Version of webcontainer:**
Hash: 70a1ff62a0f0131ac0df3c30faf487fef744ac90

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.124
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 90342262,
  "usedJSHeapSize": 86665498,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by d3lm** [comment] 2021-07-01 20:52
Yes, that's correct. It's on our radar and roadmap to update the URL bar properly in the preview window. For now, I suggest to just open the URL in another browser tab and the URL bar will update. This is currently only a limitation of the preview window right in the editor.

**Comment by cliffordfajardo** [comment] 2021-12-04 22:45
I also experienced the preview bar's URL not updating which was very confusing.
I am adding my experience as a data point 

## Steps to reproduce:
1. Visit the following stackblitz URL:
   - https://stackblitz.com/edit/github-de7jbv?file=src/App.tsx
2. Click on one of the links on the page, and observe that the preview pane's URL is not updating.

https://user-images.githubusercontent.com/6743796/144726779-9fb2a554-ec2c-4b0b-a2f6-a229d79f9a0b.mp4

## Expected behavior
- clicking a link should update the URL
- clicking a link should update the URL and if I the refresh icon OR hit enter on the preview pane's URL bar it should reload the page and retain the URL

**Comment by d3lm** [comment] 2021-12-05 22:11
Hey! Yes, as I mentioned, this is not a bug strictly speaking and rather a limitation of the URL bar for the preview window. I'd suggest to open the page in a separate browser tab / window and then you can just rely on the browser's built-in address bar, at least for the time being. We are working on another generation of the editor which comes with a whole bunch of improvements.

**Comment by cliffordfajardo** [comment] 2021-12-05 22:19
@d3lm - exciting! Out of pure curiosity (_no pressure & not demanding anything_), do you know when that new editor experience will release?

I have been enjoying stackblitz 💙 a lot lately & can't wait to see what's in store

**Comment by d3lm** [comment] 2021-12-06 07:42
Glad to hear you've been enjoying it 😍

I can't promise an exact date but the plans are Q1 / Q2 2022.

**Comment by SamVerschueren** [comment] 2023-03-10 07:58
Duplicate of #611 .

**Closed by SamVerschueren** 2023-03-10 07:58 UTC
Labels: tracked
