### ISSUE TITLE
Remix Starter: 'Upgrade Required'

### ISSUE THREAD

**Issue by msquinn** [stackblitz/webcontainer-core#488] opened 2021-12-14 15:37 UTC
### Describe the bug

Just ran the remix starter and the client loads on port 3000. However, the server on 8002 just throws a error code 426 'Upgrade required' when requests are made to it. I haven't touched the code in the starter. 

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-vrpklr

### Steps to reproduce

1. Open remix starter
2. Open Network tab
2. See all requests to server erroring out with 426 'Upgrade required'

### Expected behavior

Expect server calls to succeed and app to function as intended.

### Screenshots

<img width="448" alt="Screen Shot 2021-12-14 at 9 35 02 AM" src="https://user-images.githubusercontent.com/11398629/146029603-627e6d94-48af-433c-a420-575e9a5255d0.png">

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 96152271,
  "usedJSHeapSize": 93456983,
  "jsHeapSizeLimit": 4294705152
}
Hash = 731360fb19d99dfc563f19370095b1e3465a14ed
```

**Comment by tony19** [comment] 2021-12-14 16:41
Duplicate of #435

**Comment by jrvidal** [comment] 2021-12-14 21:08
@msquinn  Does the comment in https://github.com/stackblitz/webcontainer-core/issues/341#issuecomment-936290408 clarify things? Do you observe the site being rendered correctly after waiting enough?

**Comment by jrvidal** [comment] 2022-02-15 10:26
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.

**Closed by jrvidal** 2022-02-15 10:26 UTC
Labels: needs more info

**Comment by elix1er** [comment] 2024-09-14 04:19
still

**Comment by ziudeso** [comment] 2025-04-12 09:56
For me changing the default vite port did the trick e.g.:
```
  server: {
    port: 5111,
  },
```
