### ISSUE TITLE
 Notify Button Will Not Display

### ISSUE THREAD

**Issue by 28081998** [stackblitz/webcontainer-core#634] opened 2022-03-18 05:41 UTC
### Describe the bug

Angular Getting Started In Products Alert Component Notify Button Will not Display.Pass Data To A Child Component Is Not Working

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-15hdz1?file=src%2Fapp%2Fproduct-alerts%2Fproduct-alerts.component.html

### Steps to reproduce

product-alert-component.html
product-list-component.html

### Expected behavior

display notify button but it's not working

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 99.0.4844.51
Major version = 99
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 127048240,
  "usedJSHeapSize": 113384140,
  "jsHeapSizeLimit": 2172649472
}
Hash = 081c5c65a05b637353c8026163d5940db2997cac
```

**Comment by jrvidal** [comment] 2023-03-03 09:25
Duplicate of https://github.com/stackblitz/webcontainer-core/issues/737

**Closed by jrvidal** 2023-03-03 09:25 UTC
