### ISSUE TITLE
Doesn't support streaming response

### ISSUE THREAD

**Issue by lili21** [stackblitz/webcontainer-core#929] opened 2022-12-28 09:38 UTC
### Describe the bug

the streaming response doesn't return immediately. Instead it wait for 3 seconds.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-tzulpt?file=app%2Froutes%2Fstreaming-ssr-route2-multiple-api-calls.tsx,app%2Fentry.client.tsx,app%2Fentry.server.tsx,package.json,app%2Froutes%2Fstreaming-ssr-route1-one-api-call.tsx

### Steps to reproduce

1. click the second link
2. wait for the response

### Expected behavior

it should response without delay.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 118357675,
  "usedJSHeapSize": 114750103,
  "jsHeapSizeLimit": 2172649472
}
Hash = 6ebe18b1e1db1833797e3e4eb6ff802c375ee61b
```

**Comment by d3lm** [comment] 2023-02-22 14:40
This is possibly a duplicate of [#966](https://github.com/stackblitz/webcontainer-core/issues/966).

**Comment by Nemikolh** [comment] 2023-05-23 16:51
Hey @lili21 ! We have now support for HTTP streaming and have fixed an issue with our runtime breaking hydration which means that your second link now works as expected. :tada:

**Closed by Nemikolh** 2023-05-23 16:51 UTC
