### ISSUE TITLE
ng generate component gives error

### ISSUE THREAD

**Issue by kasdega** [stackblitz/webcontainer-core#610] opened 2022-02-23 19:58 UTC
### Describe the bug

~/projects/angular-quymjb
❯ ng generate component product-alerts
An unhandled exception occurred: Cannot set property global of #<Object> which has only a getter
See "/tmp/ng-WOUxOl/angular-errors.log" for further details.

~/projects/angular-quymjb
❯ ng generate component product-details
An unhandled exception occurred: Cannot set property global of #<Object> which has only a getter
See "/tmp/ng-aijduN/angular-errors.log" for further details.

~/projects/angular-quymjb
❯ 

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-quymjb?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html

### Steps to reproduce

1. click the plus to start another terminal
2. enter: ng generate component product-details

### Expected behavior

according to the angular.io website this should generate a component but it gives and error

** I manually entered in the product-alerts component because this error occured.

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

<img width="1380" alt="2022-02-23_13h56_42" src="https://user-images.githubusercontent.com/9752288/155397901-ff7a08e6-f8e8-4161-a302-6c0373d4fcf7.png">

### Platform

```
Browser name  = Chrome
Full version  = 97.0.4692.99
Major version = 97
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 115633022,
  "usedJSHeapSize": 106413258,
  "jsHeapSizeLimit": 4294705152
}
Hash = 60eafec8d3c353b6b62cb733670ec59f842c88b1
```

**Comment by d3lm** [comment] 2022-02-24 07:58
Duplicate of #604

**Closed by d3lm** 2022-02-24 07:58 UTC
