### ISSUE TITLE
Error executing command "ng generate component product-alert"

### ISSUE THREAD

**Issue by vafgus** [stackblitz/webcontainer-core#609] opened 2022-02-23 16:23 UTC
### Describe the bug

Message Error: An unhandled exception occurred: Cannot set property global of #<Object> which has only a getter
See "/tmp/ng-HB3xaS/angular-errors.log" for further details.

Log: ==> /tmp/ng-HB3xaS/angular-errors.log <==
    at Script.runInContext (https://zydcpr--run.w.staticblitz.com/blitz.60eafec8d3c353b6b62cb733670ec59f842c88b1.js:6:336277)
    at Script.runInNewContext (https://zydcpr--run.w.staticblitz.com/blitz.60eafec8d3c353b6b62cb733670ec59f842c88b1.js:6:336385)
    at wrap (/home/projects/zydcpr--run/node_modules/@angular/cli/models/schematic-engine-host.js:170:35)
    at SchematicEngineHost._resolveReferenceString (/home/projects/zydcpr--run/node_modules/@angular/cli/models/schematic-engine-host.js:61:40)
    at SchematicEngineHost.createSchematicDescription (/home/projects/zydcpr--run/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:181:34)
    at SchematicEngine.createSchematic (/home/projects/zydcpr--run/node_modules/@angular-devkit/schematics/src/engine/engine.js:228:38)
    at CollectionImpl.createSchematic (/home/projects/zydcpr--run/node_modules/@angular-devkit/schematics/src/engine/engine.js:80:29)
    at GenerateCommand.getSchematic (/home/projects/zydcpr--run/node_modules/@angular/cli/models/schematic-command.js:150:27)
    at GenerateCommand.initialize (/home/projects/zydcpr--run/node_modules/@angular/cli/models/schematic-command.js:63:36)

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/app.component.ts

### Steps to reproduce

ng generate component product-alert

### Expected behavior

I hope to generate a component

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 98.0.4758.102
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87888006,
  "usedJSHeapSize": 84567750,
  "jsHeapSizeLimit": 4294705152
}
Hash = 60eafec8d3c353b6b62cb733670ec59f842c88b1
```

**Comment by d3lm** [comment] 2022-02-24 07:58
Duplicate of #604

**Closed by d3lm** 2022-02-24 07:58 UTC
