### ISSUE TITLE
BUG: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by jackyef** [stackblitz/webcontainer-core#91] opened 2021-05-25 14:55 UTC
---
name: Bug report
about: Create a report to help us improve
title: 'Error when trying to run start script'
labels: ''
assignees: ''

---

**Describe the bug**
When trying to run the `start` script from this [repo](https://stackblitz.com/github/css-for-js/scrollburglars), the process failed with the following error message:
```
TypeError: The "path" argument must be of type string. Received undefined
    at validateString (https://llqipbaor--github.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:32657)
    at Object.join (https://llqipbaor--github.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:90261)
    at Object.eval (/projects/llqipbaor.github/node_modules/live-server/live-server.js:17:23)
    at Object.function (https://llqipbaor--github.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:19819)
    at Module._compile (https://llqipbaor--github.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187549)
    at Object.Module._extensions..js (https://llqipbaor--github.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187908)
    ...
```

**Link to the blitz that caused the error**
https://stackblitz.com/github/css-for-js/scrollburglars

**To Reproduce**
1. Go to https://stackblitz.com/github/css-for-js/scrollburglars
2. Wait for dependencies to be installed
3. Run `npm run start`

**Expected behavior**
The local http server should run successfully.

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 178886401,
  usedJSHeapSize: 169434089,
  jsHeapSizeLimit: 4294705152
}

**Comment by KwintenP** [comment] 2021-05-27 07:18
Same issue (?)-> https://stackblitz.com/github/SAP/openui5-sample-app

**Comment by SamVerschueren** [comment] 2021-05-27 11:07
I investigated this and it's not the same root cause. The issue here is that we don't have a `HOME` environment variable. We already fixed this internally and will land today or tomorrow. To fix this for now you can set it yourself by running `HOME=/ npm start`.

**Comment by jackyef** [comment] 2021-05-27 11:32
Thanks a lot @SamVerschueren! I noticed that image assets aren't served properly in the [blitz](https://stackblitz.com/github/css-for-js/scrollburglars?file=03-blog-example%2Fassets%2Fremote-work.jpg). Is this a already known issue as well?
 🤔 
![image](https://user-images.githubusercontent.com/7252454/119818747-c8ddd180-bf19-11eb-8dc0-4009da243b6b.png)

**Comment by SamVerschueren** [comment] 2021-05-27 12:51
How did you import the project? Did you use a GitHub import?

**Comment by jackyef** [comment] 2021-05-27 14:15
I used the trick mentioned in this [tweet](https://twitter.com/stackblitz/status/1397193629534494722), going to typing https://githubblitz.com/css-for-js/scrollburglars to the browser address bar.

**Comment by SamVerschueren** [comment] 2021-05-27 16:54
Would you mind creating a new issue for this 🙏 ? So we can track them separately. I've created an internal PR to fix this without the `HOME=/` hack 😂 .

**Comment by jackyef** [comment] 2021-05-28 04:11
Sure! I've created one at #112. Thanks for your help!

**Comment by SamVerschueren** [comment] 2021-06-02 06:17
This is now fixed in production 🎉 !

**Closed by SamVerschueren** 2021-06-02 06:17 UTC
Labels: bug, core
