### ISSUE TITLE
zlib.brotliCompressSync creates an error

### ISSUE THREAD

**Issue by brawaru** [stackblitz/webcontainer-core#1064] opened 2023-05-04 14:00 UTC
### Describe the bug

Calling `require('zlib').brotliCompressSync` throwns a cryptic error:

```
> node index.cjs

TypeError: r.init is not a function
    at BrotliCompress.Brotli (https://nodeg3zyyl-xixt.w-corp.staticblitz.com/blitz.d830b1a2.js:35:1995611)
    at new BrotliCompress (https://nodeg3zyyl-xixt.w-corp.staticblitz.com/blitz.d830b1a2.js:35:1995786)
    at Object.brotliCompressSync (https://nodeg3zyyl-xixt.w-corp.staticblitz.com/blitz.d830b1a2.js:35:1994202)
    at Object.eval (file:///home/projects/node-g3zyyl/index.js:3:4)
    at Object.function (https://nodeg3zyyl-xixt.w-corp.staticblitz.com/blitz.d830b1a2.js:44:144590)
    at Module._compile (https://nodeg3zyyl-xixt.w-corp.staticblitz.com/blitz.d830b1a2.js:35:244076)
    at Module._extensions..js (https://nodeg3zyyl-xixt.w-corp.staticblitz.com/blitz.d830b1a2.js:35:244741)
    at Module.load (https://nodeg3zyyl-xixt.w-corp.staticblitz.com/blitz.d830b1a2.js:35:242766)
    at Module._load (https://nodeg3zyyl-xixt.w-corp.staticblitz.com/blitz.d830b1a2.js:35:240331)
    at Function.executeUserEntryPoint [as runMain] (https://nodeg3zyyl-xixt.w-corp.staticblitz.com/blitz.d830b1a2.js:35:1079923)
```

This breaks packages like `ts-node` that rely on zlib.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-g3zyyl?file=package.json

### Steps to reproduce

1. Import `zlib`, using `require('zlib')` or `import zlib from 'zlib'`
2. Try using `brotliCompressSync`

### Expected behavior

It works like it does in regular Node.js (code in sandbox should print `CwKAInV3dSID` to console)

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

N/A

### Platform

- OS: Windows 10 Version 21H1
- Browser: Microsoft Edge
- Version: 112.0.1722.64 (Offizielles Build) (64-Bit) 

### Additional context

N/D

**Comment by jrvidal** [comment] 2023-05-05 06:39
Thanks for the report, I'm closing this as a duplicate of https://github.com/stackblitz/webcontainer-core/issues/339 (Brotli support)

**Closed by jrvidal** 2023-05-05 06:39 UTC
