### ISSUE TITLE
Specified Git commit message ignored

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#318] opened 2021-09-05 21:58 UTC
### Describe the bug

When commiting, the default commit message (e.g., 2 files modified) is used instead of the specified one.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vite-vue2-prismic-blog-demo

### Steps to reproduce

1. Go to blitz.
2. Edit a file.
3. Click **Commit** button at the top.
4. In the Commit Message dialog, change the message to anything other than the default.
5. Open the GitHub repo, and observe the commit message is the default message (e.g., "2 files modified").

### Expected behavior

The specified commit message is used in the commit.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by HeyGarrison** [comment] 2021-09-14 17:54
@tony19 is the repo that you're working with public by chance?

I just fixed a bug (not in production yet) where we were double committing changes. Would love to see if that's what is happening here.

**Comment by tony19** [comment] 2021-09-16 23:38
@HeyGarrison The issue was reported against a private repo, but I just tried it on a different public repo, and the problem is there as well.

StackBlitz: https://stackblitz.com/edit/vue3-test2
GitHub repo: https://github.com/tony19-sandbox/vue3-test

**Comment by SamVerschueren** [comment] 2023-02-22 10:40
I've just tested this feature again and I'm not able to reproduce this. I'm closing this issue as I think this was resolved a while ago. Feel free to create a new issue if you still run into bugs with the git integration.

**Closed by SamVerschueren** 2023-02-22 10:40 UTC
Labels: git
