### ISSUE TITLE
Cannot install private npm packages

### ISSUE THREAD

**Issue by gbbarroso** [stackblitz/webcontainer-core#76] opened 2021-05-23 21:29 UTC
**Describe the bug**
Cannot install private npm packages. Looks like I can set the NPM_TOKEN env var, but it always tries pulling from https://nr.staticblitz.com/ we need a way to change that

**To Reproduce**
1. Add a npm private package to your package.json
2. `npm i`

**Expected behavior**
I think we either need NPM_TOKEN to be passed or a way to point it to npm server directly

**Comment by KwintenP** [comment] 2021-05-25 08:00
Hi, 

We wrote our own npm client that uses some neat tricks to make it as fast as it is today. This does mean that we currently don't have support yet for private npm registries. It's def on our roadmap for the (near) future 👍 

🙏 for reporting

**Comment by SuperOleg39** [comment] 2021-06-09 07:20
Hi!

Private registry support also not available in Stackblitz Enterprise Edition? For SSR applications

**Comment by jrvidal** [comment] 2021-10-08 08:43
This is a duplicate of #21

**Closed by jrvidal** 2021-10-08 08:43 UTC
Labels: enhancement, turbo
