### ISSUE TITLE
Not Able to start development server

### ISSUE THREAD

**Issue by cpPratikParshuramChavan** [stackblitz/webcontainer-core#395] opened 2021-11-10 17:16 UTC
### Describe the bug

NextJs Example Link = https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-portals?file=package.json

### Link to the blitz that caused the error

https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-portals?file=package.json

### Steps to reproduce

Go to [](https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-portals?file=package.json)

### Expected behavior

Development server should start.

### Screenshots

![image](https://user-images.githubusercontent.com/84561116/141160467-adbbb95b-f9cc-4a8f-8b3e-20b9d2886a56.png)

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 80465930,
  "usedJSHeapSize": 76941126,
  "jsHeapSizeLimit": 4294705152
}
Hash = d83b9b15484f32317787d8c7cc41da5651102bdc
```

**Comment by jrvidal** [comment] 2021-11-11 08:27
@cpPratikParshuramChavan Can you try again? I can't reproduce, and we've recently released a fix related to Next.js.

**Comment by jrvidal** [comment] 2022-01-10 10:23
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.

**Closed by jrvidal** 2022-01-10 10:23 UTC
Labels: needs more info
