### ISSUE TITLE
Repo with master branch (main) causes github import to fail

### ISSUE THREAD

**Issue by willemneal** [stackblitz/webcontainer-core#312] opened 2021-08-29 18:37 UTC
### Describe the bug

Since the github component assumed that master branch would be used the application notified me that it failed to find a master branch.  Then it proceeded to spin and I couldn't figure out how to change the branch.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-f8erox

### Steps to reproduce

1. try importing from https://github.com/near/runner-js/
2. See popup at bottom that it failed to find master
3. Get stuck waiting for master to be found.

### Expected behavior

To allow me to choose another branch.

### Screenshots

<img width="129" alt="Screen Shot 2021-08-29 at 14 26 16" src="https://user-images.githubusercontent.com/1483244/131261559-f90445cc-38a9-4929-af07-76cf47c64053.png">

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.115
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 92763237,
  "usedJSHeapSize": 74838921,
  "jsHeapSizeLimit": 4294705152
}
Hash = 8ffc536d8181e8b30c228dec423d18afae547c40
```

**Comment by willemneal** [comment] 2021-08-29 18:42
I just added a master to it to test if that fixes it and it did.

**Comment by tony19** [comment] 2021-08-29 23:22
Duplicate of #195

**Closed** 2021-08-30 18:30 UTC
