### ISSUE TITLE
Github change state lost after refreshing the pate

### ISSUE THREAD

**Issue by ClassicOldSong** [stackblitz/webcontainer-core#817] opened 2022-09-29 21:51 UTC
If the change wasn't committed to GitHub before refreshing the page, the change status will lost. Contents modified were saved to the project but only newer changes will be committed after refreshing.

**Comment by d3lm** [comment] 2023-03-10 10:29
Thanks for the report! I think this may be a duplicate of https://github.com/stackblitz/core/issues/2421. I think we can use that other issue to track this one.

**Closed by d3lm** 2023-03-10 10:29 UTC
