### ISSUE TITLE
Event loop bug

### ISSUE THREAD

**Issue by anson09** [stackblitz/webcontainer-core#980] opened 2023-03-01 07:28 UTC
### Describe the bug

bug 1:
nodejs run one task and then one microtask since node 11, here in the container with nodejs 16 we get an older behavior 
```js
setImmediate(() => {
  console.log('immediate 1');
  Promise.resolve().then(() => {
    console.log('micro-task');
  });
});
setImmediate(() => {
  console.log('immediate 2');
});
```

bug 2: 
when running in microTaskQueu, it should exhaust this queue before jumping to nextTickqueue
```js
queueMicrotask(() => {
  queueMicrotask(() => {
    console.log('microTask');
  });
  process.nextTick(() => {
    console.log('nextTick');
  });
});

```

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-b76fas?file=bug1.js

### Steps to reproduce

run `npm start` in stackblitz terminal 

### Expected behavior

bug 1:
// output: immediate 1 -> immediate 2 -> micro-task
// expected: immediate 1 -> micro-task -> immediate 2

bug 2:
// output: nextTick -> microTask
// expected: microTask -> nextTick

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/2612873/222067534-92597040-2975-4e0b-9554-498a47b4c5fd.png)

### Platform

- OS: macOS 13.2.1
- Browser: Chrome 110

**Comment by d3lm** [comment] 2023-03-06 09:06
Hey there! Thanks for reporting this issue and I can confirm that the event loop is not entirely the same as on local especially when micro tasks are in the mix. Unfortunately this is really hard to be fixed on our side due to browser limitations, or without trading performance. Out of curiosity, did you run into a specific issue with the event loop or were you just trying to understand it?

**Comment by anson09** [comment] 2023-03-07 03:57
Thanks for replying. I found this issue when I dug into how the event loop works and wanted to make a quick demo in https://node.new to prove my research, but the output confused me, so I compared it to my several local node.js results. Anyway, it's ok to close this issue if it's limited by browsers now. Webcontainer is awesome.

**Comment by d3lm** [comment] 2023-03-07 17:34
Oh gotcha. Yea it's a little unfortunate that the event loop is slightly different and if possible we do intend to close the gap as much as possible. It's just a little difficult without scarifying performance too much. Thanks for reporting the issue tho, and I hope you can still use WebContainer for other things. Usually relying on the exact behavior of the event loop is something that I would avoid, even if you can somewhat rely on it locally. But it could also be a source of bugs.

I am going to close this issue for now, but keeping this in mind and also tracking it internally so we can improve the event loop over time as browser APIs improve, or new APIs / capabilities are added.

**Closed by d3lm** 2023-03-07 17:34 UTC

**Comment by ocodista** [comment] 2023-08-05 20:04
Hey, any updates on this issue?

I also saw this on the website of webcontainers while studying event loop.

I would like to use WebContainers but the order being different than the node is a current blocker to me.

**Comment by ocodista** [comment] 2023-08-05 20:05
![image](https://github.com/stackblitz/webcontainer-core/assets/19851187/fb7e2bfb-01a6-43e2-bd69-e0118edf8120)

This is the code I'm using

```javascript
```

**Comment by ocodista** [comment] 2023-08-05 20:06
This is the result when running on node
![image](https://github.com/stackblitz/webcontainer-core/assets/19851187/177025d7-a559-4d39-bdde-b1545d223cb6)
