### ISSUE TITLE
interval variable declared type is incorrect

### ISSUE THREAD

**Issue by DsanchezPerez** [stackblitz/webcontainer-core#827] opened 2022-10-12 09:03 UTC
### Describe the bug

The interval variable used to hold the setInterval function reference is declared as number|undefined but it should be declared as interval: NodeJS.Timer|number|undefined; is the correct syntax.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fad-banner.component.ts

### Steps to reproduce

1. Code variable declaration is not syntaxial correct.

### Expected behavior

No compiler errors or warnings to provide accurate information.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 105.0.0.0
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 163843323,
  "usedJSHeapSize": 156415363,
  "jsHeapSizeLimit": 4294705152
}
Hash = ea2f6b48b77806aba8e6fe3b6311530cc7674f64
```

### Additional context

Promote truthful and accurate information to demonstrate higher education still means elite members of a field of study.

**Comment by SamVerschueren** [comment] 2022-10-12 14:14
Hey @DsanchezPerez!

Can you link where you pressed the `Open in StackBlitz` linke? Because the link of the reproduction is a dynamic link so I cannot check where this is incorrect.

So the thing here is that `setInterval()` in the browser returns a `number`. So it is actually correct. If you want Node.js types, you need to install `@types/node`.

Before installing `@types/node`

![image](https://user-images.githubusercontent.com/1913805/195366642-d15bf116-c7d3-4561-b19a-51254b2d2aeb.png)

After installing `@types/node`

![image](https://user-images.githubusercontent.com/1913805/195366751-120c6c9e-b25e-4b31-9bf7-de3dcb04dbb1.png)

**Comment by SamVerschueren** [comment] 2023-03-08 11:50
Closing this as this is the same behaviour in VSCode on local. If you don't install `@types/node`, it will use the browser definition of `setInterval()`.

![image](https://user-images.githubusercontent.com/1913805/223705939-669db68d-af2a-4fa9-bb3b-962481c4ea61.png)

**Closed by SamVerschueren** 2023-03-08 11:50 UTC
