### ISSUE TITLE
Running Vite on Stackblitz

### ISSUE THREAD

**Issue by aymanapatel** [stackblitz/webcontainer-core#254] opened 2021-07-20 04:32 UTC
### Describe the bug

It is not possible to run Vite on Stackblitz

```
❯ npm run dev
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/vite-vszkxk?file=package.json

### Steps to reproduce

1. Run `npm run dev`

Error: 

```
~/projects/vite
❯ npm run dev
$ vite
Error: esbuild: Failed to install correctly

Make sure you don't have "ignore-scripts" set to true. You can check this with
"npm config get ignore-scripts". If that returns true you can reset it back to
false using "npm config set ignore-scripts false" and then reinstall esbuild.

If you're using npm v7, make sure your package-lock.json file contains either
"lockfileVersion": 1 or the code "hasInstallScript": true. If it doesn't have
either of those, then it is likely the case that a known bug in npm v7 has
corrupted your package-lock.json file. Regenerating your package-lock.json file
should fix this issue.

```

2. If I try to set npm config , I get this error: 

```
❯ npm config set ignore-scripts false
┌─ WARNING ──────────────────────────────────────────────────────────────────────────┐
│ It seems you are trying to use `npm`. This is a compatibility layer which uses     │
│ `turbo` instead, a blazingly fast package manager designed for the web. If you     │
│ wish to hide this warning, you can do so by setting `warnings.npm = false` inside  │
│ "/home/.turbo/.turborc.json" or use `turbo` directly.                              │
└────────────────────────────────────────────────────────────────────────────────────┘
ERR!: Unknown command `config`
```

### Expected behavior

Vite should work by default.

### Platform

```
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 63442039,
  "usedJSHeapSize": 59425299,
  "jsHeapSizeLimit": 4294705152
}
Hash = 84452ea99b8c6a79e19cae2129beaf85d5da007c
```

**Comment by tony19** [comment] 2021-07-23 05:01
This is probably a duplicate of #8

**Comment by SamVerschueren** [comment] 2021-07-23 07:26
Thanks for expressing interest in Vite @aymanapatel. We're working hard to ship new features and hope we can give you an update on this one soon. Can't give you an exact estimate though.

Closing as a duplicate of #8. Thanks for the reference @tony19 !

**Closed by SamVerschueren** 2021-07-23 07:26 UTC
