### ISSUE TITLE
BUG: parcel throws error in `tiny-inflate` package

### ISSUE THREAD

**Issue by oe** [stackblitz/webcontainer-core#120] opened 2021-05-29 05:56 UTC
**Link to the blitz that caused the error**
https://stackblitz.com/edit/github-fshd7k?file=package.json

**Steps to reproduce:**

1. Go to <https://stackblitz.com/edit/github-fshd7k?file=package.json>, and waiting until the project initialized
2. run `yarn dev`, error and not working
3. run `yarn build`, error, not working
4. add `dist` folder in the project, then run `yarn rrr`, no error but not working( dist folder not removed

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots:**
![image](https://user-images.githubusercontent.com/1655294/120059645-64d81c00-c085-11eb-80e4-a5e157a86992.png)

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 89.0.4389.114
Major version = 89
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 71350001,
  "usedJSHeapSize": 60800841,
  "jsHeapSizeLimit": 4294705152
}

**Comment by SamVerschueren** [comment] 2021-06-02 06:25
@oe Thanks for reporting the issues you run into. Let's break the issue down, because it has multiple things in it.

1. There was indeed a bug with `&&` in npm scripts which is now fixed.
2. The `yarn rrr` command seems to be working on my end. Maybe it had something to do with issue `1` which we fixed, but it seems to be working now.
3. I haven't looked into `parcel` before, but yes it looks like it has some issues.

Because issue `1` and `2` are resolved now, let me change the issue title to `parcel` instead and I'll create an internal ticket so we can look into it.

**Comment by jrvidal** [comment] 2021-09-15 13:12
@oe I tried reproducing this and we now throw when trying to require [deasync](https://www.npmjs.com/package/deasync), which relies on native bindings, which we don't support.

We could try to polyfill but success it's not guaranteed :disappointed:  It seems that parcel@v2 does not use deasync at least...

**Comment by oe** [comment] 2021-09-16 05:14
@jrvidal  parcel@v1  is still widely used, it would be very nice if parcel@v1 could work well on webcontainer🙏🏻

You may visit https://www.npmjs.com/package/parcel-bundler to check its weekly downloads

**Comment by jrvidal** [comment] 2021-09-16 13:34
@oe We did some monkey-patching of `deasync` through an internal polyfill. You'll see now that the blitz you linked works :tada:. 

However there are a few caveats: 
* `deasync` won't really work if it is actually run at some point.
* There are some error messages related to missing features in the shell.

Since they don't seem to be deal breakers, I'm going to close this. Please feel free to open more issues if you find something else.

Thanks for the report!

**Closed by jrvidal** 2021-09-16 13:34 UTC
Labels: bug, core, tracked

**Comment by oe** [comment] 2021-09-17 07:23
Great🎉.  It works!
