### ISSUE TITLE
No angular generator option on dropdown menu

### ISSUE THREAD

**Issue by mdlawrenceusa** [stackblitz/webcontainer-core#379] opened 2021-11-04 16:10 UTC
### Describe the bug

When I <right-click> on app the dropdown menu does not include an option for the Angular Generator.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-kijuuh?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html

### Steps to reproduce

When I <right-click> on app the dropdown menu does not include an option for the Angular Generator.

### Expected behavior

There is usually a menu option for the angular generator

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 85290658,
  "usedJSHeapSize": 77874170,
  "jsHeapSizeLimit": 4294705152
}
Hash = eb19bc088249a645473767848622a1d98c51b8f3
```

**Comment by geromegrignon** [comment] 2021-11-04 16:22
Duplicate of #377

**Comment by mdlawrenceusa** [comment] 2021-11-04 16:24
Thank you. Sorry for the duplicate.

**Closed** 2021-11-05 08:12 UTC
