### ISSUE TITLE
cannot install dependencies

### ISSUE THREAD

**Issue by firekoala** [stackblitz/webcontainer-core#413] opened 2021-11-19 10:56 UTC
### Describe the bug

after i join repo and try to install dependecies with npm install x it says:

warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ 𐄂 Failed
ERR!: The "to" argument must be of type string. Received null

error Command failed with exit code 1

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-1dmxz2?file=package.json

### Steps to reproduce

join repo
npm install firebase or anything else.

### Expected behavior

i expect to install dependencies without bugs

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 74784087,
  "usedJSHeapSize": 67870807,
  "jsHeapSizeLimit": 2172649472
}
Hash = 5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b
```

**Comment by jrvidal** [comment] 2021-11-19 12:40
Hey @firekoala thanks for the report. I can't seem to reproduce:

https://user-images.githubusercontent.com/1636604/142624261-2d8ef2f3-47dc-4ea8-aa5d-87a8c3af8876.mp4

Do you observe the issue when opening the blitz and auto-install kicks in? Do you see any funny messages in the browser console?

**Comment by firekoala** [comment] 2021-11-19 13:12
Hello, i am trying to debug it right now by reloading chrome /deleting repo
and reinstalling it and it works half the time, the other half its the same
problem, its really weird.
Its the same with new projects with no repo.

**Comment by jrvidal** [comment] 2022-03-11 13:55
@firekoala Are you still affected by this issue?

**Comment by kc0tlh** [comment] 2022-04-22 13:24
Closing this issue due to lack of reproducibility. Feel free to re-open if it pops up again!

**Closed by kc0tlh** 2022-04-22 13:24 UTC
Labels: needs more info
