### ISSUE TITLE
Failed to run start command

### ISSUE THREAD

**Issue by RealisticHassan** [stackblitz/webcontainer-core#732] opened 2022-06-27 12:51 UTC
### Describe the bug
failed to run start command

[https://stackblitz.com/run?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html](url)

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html

### Steps to reproduce

while running the angular-practice-project that is provided in angular official documentation I got the error "filed to run the commad"

### Expected behavior

the code should run properly

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 103.0.5060.53
Major version = 103
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37
performance.memory = {
  "totalJSHeapSize": 67442897,
  "usedJSHeapSize": 63701401,
  "jsHeapSizeLimit": 2172649472
}
Hash = c4393a56cbb8e2fec13bc31575603ce9568f347d
```

**Comment by SamVerschueren** [comment] 2022-06-27 12:55
I believe this is a duplicate of #724. We are aware of the issue and trying to resolve it.

**Closed by SamVerschueren** 2022-06-27 12:55 UTC
