### ISSUE TITLE
BUG: projects generated via Angular CLI's `ng new` can't be saved

### ISSUE THREAD

**Issue by IgorMinar** [stackblitz/webcontainer-core#109] opened 2021-05-28 00:44 UTC
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-dbtp7g

**Steps to reproduce:**

1. create a new node.js project using https://stackblitz.com/fork/node
2. run `npm install -D @angular/cli` in the terminal
3. run `ng new example-app --defaults --skip-git`
4. try to save the project and reload the page

**Expected behavior:**

expected: project is saved and restored after page reloads
actual:
  - when trying to reload the page, stackblitz warns me that the project is not saved
  - any attempts to save the project result in `VM1638:1 PATCH https://stackblitz.com/api/projects/node-b2wjv7 422` in the console
  - ignoring and reloading the page results in the project state not being preserved

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 132226467,
  "usedJSHeapSize": 118165047,
  "jsHeapSizeLimit": 4294705152
}

**Comment by EricSimons** [comment] 2021-05-28 01:23
Thanks for reporting this! Really odd this errored for you because it seemed to work for others (like https://twitter.com/markwhitfeld/status/1395669545063436293?s=21)

Will investigate this tomorrow morning and see if we’ve had a regression or something else 🙏

**Comment by IgorMinar** [comment] 2021-05-28 02:24
I can generate the app and run the devserver as well. I just can't save the project and share it with others.

Notice that in Mark's screen cast, the files remain unsaved. I suspect that if he tried it, it would not work.

**Comment by IgorMinar** [comment] 2021-05-28 02:28
Btw I've seen similar problems with stackblitz in the past when my project reached certain size (total number of lines/source code bytes) - I wonder if the newly generated app is over some limit.

Thanks for looking into this.

**Comment by SamVerschueren** [comment] 2021-05-28 06:04
@IgorMinar Thanks for trying this out and reporting this issue! I've looked into it and the reason it fails is because of the `favicon.ico`. There's an issue with how images are being handled on our side. So as a quick workaround, if you remove the `favicon.ico` file you will be able to save the project. In the mean time we will look into fixing this issue 🙏 .

**Comment by IgorMinar** [comment] 2021-05-28 18:50
Interesting! Sam, thank you for looking into this and finding the culprit.

**Comment by IgorMinar** [comment] 2021-06-02 21:37
@SamVerschueren I was able to confirm that the favicon.ico was the culprit. I converted the file to a data url and was able to get the demo to work (with some limitations documented in Readme.md): https://stackblitz.com/edit/ng-webcontainer

Overall I'm super excited about the prospects of this. Awesome job team Stackblitz!

**Comment by SamVerschueren** [comment] 2021-06-04 12:15
Hey @IgorMinar, here's an update from our side.

Images are now working properly. When scaffolding out a new project however, they are placed in the root directory instead of the correct location. We're looking into this together with an issue with empty files (looking at you `app.component.css`). It got lost after I did `ng new`.

We also fixed `ng test`. So now you can run `npm test` (or `ng test`) and it will start Karma and open the URL in the preview pane showing the tests.

I've created a project which you can fork https://stackblitz.com/edit/ng-sam if you want to quickly play around with it. Or feel free to update your `ng-webcontainer` project with the `favicon.ico` etc.

I'm keeping this issue open until all issues are resolved. But wanted to keep you in the loop on the progress.

**Comment by IgorMinar** [comment] 2021-06-04 14:19
Thanks for the update Sam. I'll update my project today and let you know how it went.

**Comment by IgorMinar** [comment] 2021-06-04 22:38
I've regenerated https://stackblitz.com/edit/ng-webcontainer (following the instructions documented in the readme.md) and I can confirm that the favicon and karma issues are now resolved. I also came across a new issue that @SamVerschueren mentioned - the empty `src/app/app.component.css` file is not preserved after `ng new`. Fortunately it is preserved if I `touch` the file and then resave the project.

Awesome progress! Thank you

**Comment by SamVerschueren** [comment] 2021-06-10 17:03
@IgorMinar The issue with the empty files not being saved got fixed by @KwintenP and is deployed to production. I tested it, and when running `ng new` works entirely now and doesn't give weird results anymore 🙏 .

I looked into the list of issues you wrote down in the `ng-webcontainer` project.

> only Chrome is supported, for example Firefox and Safari, and even Chromium-based Brave are currently not
Brave does work, but the user has to allow cookies from StackBlitz.com. It's explained here https://github.com/stackblitz/webcontainer-core/blob/main/browsers/brave/brave.md. We're working at notifying the user when we detect Brave and the serviceworker fails to install. So we're definitely improving on that front. Firefox is coming, we have to get the COOP/COEP security headers right which Chrome will enforce from Chrome 92 and above if I'm not mistaken. So we can't wait too long with it. And Safari, as long as they don't add support for SharedArrayBuffer, we're basically lost in the woods.

> `ngcc` runs from scratch after each reload, causing delay for the devserver startup.
I believe `ngcc` writes in the `node_modules` which we don't store on the server and thus always have to be regenerated. I don't think there's currently something we can do about that. Syncing all `node_modules` is kinda impossible from our end.

> `src/app/app.component.css` isn't preserved correctly after a `ng new` scaffolds a new project (https://github.com/stackblitz/webcontainer-core/issues/109#issuecomment-854659697)
This is fixed now 🎉 !

I hope these answers are helpful. Feel free to close the issue if you think it was resolved. We can always discuss the other points in new issues maybe?

**Closed** 2022-01-03 22:22 UTC
Labels: bug
