### ISSUE TITLE
Renaming (changing "Project URL") causes terminal to stop functioning until refresh

### ISSUE THREAD

**Issue by agilgur5** [stackblitz/webcontainer-core#714] opened 2022-06-09 16:26 UTC
### Describe the bug

When renaming a new WebContainer, e.g. just after forking, if you change the link, the terminal will stop working. Like it won't receive any input and if you try opening a new terminal it won't load.

If you refresh the page, causing it to be renamed to the new link, the terminal starts working ok.

So seems like the rename isn't propagated everywhere immediately.

Note that renaming it back won't fix the issue either, only refreshing the page will.

### Link to the blitz that caused the error

https://stackblitz.com/edit/rpt2-issue-223?file=src%2Findex.ts

### Steps to reproduce

1. Go to literally any WebContainer
2. Click "Edit project info"
3. Modify the "Project URL" (I think this is the only one that breaks it, don't think "Title" breaks it, but can try that too with and without modifying "Project URL")
4. Try to do something in the terminal, you won't be able to. Can also try opening a new terminal and watch it fail to load
5. Refresh the page
6. Terminal works now

### Expected behavior

Modifying the "Project URL" (and possibly "Title" per above) should not cause the current terminal to stop functioning.
Ideally a refresh shouldn't be required, but if it is, Stackblitz should refresh automatically or at least notify the user, instead of the current confusing UX

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

1. Screenshot of a sample "Project URL" rename:
![Screen Shot 2022-06-09 at 12 21 04 PM](https://user-images.githubusercontent.com/4970083/172896820-17503a27-94cb-4d30-98f0-ea2729f8077c.png)

2. Screenshot of terminal no longer working after (I'm typing and nothing is coming through, so can't see the typing), as well as opening a new terminal and it not loading (can type in the new one, but no prompt ever comes up, hitting enter does nothing etc):
![Screen Shot 2022-06-09 at 12 21 31 PM](https://user-images.githubusercontent.com/4970083/172897026-a6025c4b-0f58-4e93-918b-cc9e9da3400f.png)

### Platform

```
Browser name  = Chrome
Full version  = 101.0.4951.64
Major version = 101
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 191735459,
  "usedJSHeapSize": 176580687,
  "jsHeapSizeLimit": 4294705152
}
Hash = ad37e903755d89e0f5d9999e69be73a0c6cb6bcc
```

### Additional context

Couldn't seem to find any existing issues when searching for "rename" surprisingly

**Comment by tony19** [comment] 2022-06-10 00:30
Duplicate of #689

**Comment by agilgur5** [comment] 2022-06-10 16:58
Ah indeed we have different terminology and different descriptions (I didn't use the preview window at all, only the terminal), but these are duplicates of each other.

I'll leave this open in case it's easier for a maintainer to find/address; they can feel free to close as duplicate though.

**Comment by SamVerschueren** [comment] 2023-03-06 17:19
Thanks @agilgur5 for reporting! Let's close this issue in favour of #689.

**Closed by SamVerschueren** 2023-03-06 17:19 UTC
