### ISSUE TITLE
Prompt SBOX_FATAL_MEMORY_EXCEEDED after project startup

### ISSUE THREAD

**Issue by OSpoon** [stackblitz/webcontainer-core#1099] opened 2023-06-14 03:45 UTC
### Describe the bug

After I shared the project, it caused the browser to crash upon startup, but this phenomenon did not exist before sharing.

### Link to the blitz that caused the error

https://stackblitz.com/edit/nestjs-typescript-starter-ukpkr2?file=README.md

### Steps to reproduce

The problem can be reproduced after the initial loading is successful and the default command is automatically executed

### Expected behavior

normal use

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 114.0.0.0
Major version = 114
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 116135378,
  "usedJSHeapSize": 98388718,
  "jsHeapSizeLimit": 4294705152
}
Hash = a12d8c69
```

**Comment by SamVerschueren** [comment] 2023-06-14 07:45
Closing as a duplicate of #1096.

**Closed by SamVerschueren** 2023-06-14 07:45 UTC
