### ISSUE TITLE
Astro.js example says "Upgrade Required"

### ISSUE THREAD

**Issue by stephencombs** [stackblitz/webcontainer-core#484] opened 2021-12-14 05:33 UTC
### Describe the bug

Clicking on the "Launch In Stackblitz" button on the astro examples Is just see the message "Upgrade Required" in the ouput window on the right.

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-gmrbs4?file=src%2Fpages%2Findex.astro

### Steps to reproduce

Clicking on the "Launch In Stackblitz" button on a Astro.js project

### Expected behavior

Display the compiled preview

### Screenshots

![image](https://user-images.githubusercontent.com/26053206/145939103-02345597-3374-4623-9f15-5c4121993c2e.png)

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.93
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 102117161,
  "usedJSHeapSize": 91122253,
  "jsHeapSizeLimit": 4294705152
}
Hash = c1a2f33ebdb80ec1573b6337c828d176e80f0398
```

**Comment by tony19** [comment] 2021-12-14 05:45
Duplicate of #341 

From https://github.com/stackblitz/webcontainer-core/issues/341#issuecomment-936290408:

> please note that you will still see the "Upgrade Required" message for a while: the HMR server gets responsive way sooner than the main server, but you'll eventually see the latter take over.

**Comment by jrvidal** [comment] 2021-12-14 07:49
Is #341 the issue you're seeing @stephencombs ?

**Comment by stephencombs** [comment] 2021-12-14 19:59
> 

That is correct.

**Comment by stephencombs** [comment] 2021-12-14 19:59
> Is #341 the issue you're seeing @stephencombs ?

That is correct.

**Comment by jrvidal** [comment] 2021-12-14 20:23
Great, I think this can be closed then.

**Closed by jrvidal** 2021-12-14 20:23 UTC
Labels: needs more info
