### ISSUE TITLE
NEST.JS unable to run watch mode

### ISSUE THREAD

**Issue by web-dave** [stackblitz/webcontainer-core#392] opened 2021-11-09 19:25 UTC
### Describe the bug

I've tried to run the nest server in watch mode. every change generates a error.
Process isn't reachable anymore

```
[20:22:24] File change detected. Starting incremental compilation...

[20:22:24] Found 0 errors. Watching for file changes.

jsh: command not found: ps
[Error: spawn ps ENOENT] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 12 ]
}

```

### Link to the blitz that caused the error

https://stackblitz.com/edit/nestjs-typescript-starter-glgi7f?file=src%2Fapp.service.ts&terminal=start

### Steps to reproduce

cancel npm start 
npm run start:dev
change file
Boooom

### Expected behavior

reload on change

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 90429843,
  "usedJSHeapSize": 81709063,
  "jsHeapSizeLimit": 4294705152
}
Hash = d83b9b15484f32317787d8c7cc41da5651102bdc
```

**Comment by SamVerschueren** [comment] 2021-11-10 06:26
Thanks for reporting @web-dave 🙏 ! This is a duplicate of #391. Closing this one. Feel free to continue the discussion in that issue instead.

**Closed** 2021-11-10 06:26 UTC
