### ISSUE TITLE
SVG is not displaying in Firefox

### ISSUE THREAD

**Issue by dfa1234** [stackblitz/webcontainer-core#709] opened 2022-06-07 17:16 UTC
### Describe the bug

SVG is not displaying in firefox. But is displaying in chrome very well.
It's a SVG file hosted on github that I try to display in my stackbliz project
SVG is served at this address: https://raw.githubusercontent.com/dfa1234/highcharts-gradients-vite/master/favicon.svg
The SVG is meant to be rendered by highcharts.js library
The project is using typescript (if relevant)

### Link to the blitz that caused the error

https://stackblitz.com/edit/highcharts-gradients-vite

### Steps to reproduce

1. Just open the project and look, once in firefox, once in chrome.
2. If you want to see how the SVG is loaded, it's in highchart svg-render, configured in the project file './draw-svg.ts'
here https://stackblitz.com/edit/highcharts-gradients-vite?file=README.md,src%2Fdraw-svg.ts

### Expected behavior

Enjoying nice SVG in charts

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

In Firefox the SVG is not displayed:
![image](https://user-images.githubusercontent.com/8502517/172441219-6875c5ab-df95-44aa-9216-180d4b17285e.png)

Same project on chrome with the SVG:
![image](https://user-images.githubusercontent.com/8502517/172441699-a0fa7cd2-a8c7-4d9d-909d-d3a030752658.png)

### Platform

```
Browser name  = Firefox
Full version  = 101.0
Major version = 101
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0
performance.memory = undefined
Hash = 994c02b5adfbddf10615fbd93251fe140e2a2f0e
```

**Comment by SamVerschueren** [comment] 2022-06-08 06:24
Hi @dfa1234 👋 ! This is a duplicate of #669 and you can find a [more detailed explanation](https://github.com/stackblitz/webcontainer-core/issues/669#issuecomment-1099893983) there as well.

To work around this issue, you can do two things
- Add the svg to the project and link it directly
- Use a SVG data url instead of the URL linking to GitHub as I did here https://stackblitz.com/edit/highcharts-gradients-vite-dko8u5?file=src%2Fdraw-svg.ts

If interested. Apparently [Firefox is currently working on `credentialless` mode](https://twitter.com/arthursonzogni/status/1534225718216908802) which should give the same behaviour in Firefox as you have in Chrome right now. But for now, we're stuck with `require-corp` which prevents you from loading assets from a different origin, unless explicitly granted by that origin (in this case GitHub).

**Closed by SamVerschueren** 2022-06-08 06:24 UTC
