### ISSUE TITLE
[BUG] Fork failing

### ISSUE THREAD

**Issue by geromegrignon** [stackblitz/webcontainer-core#410] opened 2021-11-17 12:10 UTC
### Describe the bug

By trying to fork an Angular Materisl project (https://stackblitz.com/run?file=src/app/slider-overview-example.ts), on clicking on **Fork**, the spinner keeps moving and there are errors in the devTools, it looks like the related error page isn't loaded though.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/slider-overview-example.ts

### Steps to reproduce

1. Go to https://stackblitz.com/run?file=src/app/slider-overview-example.ts
2. Click on **Fork**
3. Nothing happens
4. there are errors in the DevTools console

### Expected behavior

a fork is created

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by HeyGarrison** [comment] 2022-02-21 04:07
Thanks for reporting! This is probably a duplicate of #569 . Feel free to re-open if not. ❤️ ❤️ ❤️

**Closed by HeyGarrison** 2022-02-21 04:07 UTC
