### ISSUE TITLE
Failing to run the code

### ISSUE THREAD

**Issue by drveresh** [stackblitz/webcontainer-core#765] opened 2022-08-02 03:28 UTC
### Describe the bug

Hi,

Here is my simple code https://stackblitz.com/edit/node-y8yhsr?file=index.js, that is failing to run, and below is the error:

```
❯ node index.js
Running Test Node.js v16.14.2!
======= DONE =======
TypeError: Failed to fetch
    at _0x5d1ab8._fetch (https://node-y8yhsr.w.staticblitz.com/blitz.6c99c9393fc14db5c7a59ebee56b2e07fa137aaf.js:15:405390)
    at _0x5d1ab8.performHTTPCall (https://node-y8yhsr.w.staticblitz.com/blitz.6c99c9393fc14db5c7a59ebee56b2e07fa137aaf.js:15:404955)
    at _0x5d1ab8._write (https://node-y8yhsr.w.staticblitz.com/blitz.6c99c9393fc14db5c7a59ebee56b2e07fa137aaf.js:15:398954)
    at _0x5d1ab8.writeLatin1String (https://node-y8yhsr.w.staticblitz.com/blitz.6c99c9393fc14db5c7a59ebee56b2e07fa137aaf.js:15:389616)
    at _0x545af3.writeLatin1String (https://node-y8yhsr.w.staticblitz.com/blitz.6c99c9393fc14db5c7a59ebee56b2e07fa137aaf.js:15:210143)
    at https://node-y8yhsr.w.staticblitz.com/blitz.6c99c9393fc14db5c7a59ebee56b2e07fa137aaf.js:6:783438
    at writeGeneric (https://node-y8yhsr.w.staticblitz.com/blitz.6c99c9393fc14db5c7a59ebee56b2e07fa137aaf.js:6:783719)
    at Socket._writeGeneric (https://node-y8yhsr.w.staticblitz.com/blitz.6c99c9393fc14db5c7a59ebee56b2e07fa137aaf.js:6:237637)
    at Socket._write (https://node-y8yhsr.w.staticblitz.com/blitz.6c99c9393fc14db5c7a59ebee56b2e07fa137aaf.js:6:237795)
    at doWrite (https://node-y8yhsr.w.staticblitz.com/blitz.6c99c9393fc14db5c7a59ebee56b2e07fa137aaf.js:6:1012708)
```

As a user, I expect more meaningful error messages unlike the above.  The same code runs fine in my local CLI.

Please help me understand what is going on with it and fix if anything.

Thank you!

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-y8yhsr?file=index.js,package.json

### Steps to reproduce

1. npm install
2. node index.js

### Expected behavior

It should print the list of all URLs redirected from the patent link https://bit.ly/2X7gCIT

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 103.0.0.0
Major version = 103
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 102096017,
  "usedJSHeapSize": 93228645,
  "jsHeapSizeLimit": 4294705152
}
Hash = 6c99c9393fc14db5c7a59ebee56b2e07fa137aaf
```

**Comment by SamVerschueren** [comment] 2022-08-02 07:48
Hi @drveresh. Thanks for reaching out.

This is a duplicate of https://github.com/stackblitz/webcontainer-core/issues/142#issuecomment-853873812. This is due to CORS not being configured on the endpoint you're trying to fetch from.

If you're using Chrome, there's an extension called `Allow Cors: Access-Control-Allow-Origin` which you could use to circumvent this issue. I did notice however that it throws a different error, because the bitly URL redirects to `http://github.com` instead of `https://github.com`. But it should work with a different URL I would assume.

**Closed by SamVerschueren** 2022-08-02 07:48 UTC
