### ISSUE TITLE
Cannot `npm install wagmi`

### ISSUE THREAD

**Issue by zouhangwithsweet** [stackblitz/webcontainer-core#702] opened 2022-05-25 07:49 UTC
### Describe the bug

I cannot run `npm install wagmi`.
<img width="362" alt="image" src="https://user-images.githubusercontent.com/21095710/170209423-211197aa-711e-41f5-bd94-bf00131450a4.png">

https://www.npmjs.com/package/wagmi

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-fnpv86

### Steps to reproduce

1. `npm install && npm dev`

### Expected behavior

It can be installed

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 101.0.4951.64
Major version = 101
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 90277859,
  "usedJSHeapSize": 80235911,
  "jsHeapSizeLimit": 2172649472
}
Hash = 670e941965b7233a68cb924e1ca43e6a0f35bf71
```

**Comment by SamVerschueren** [comment] 2022-05-25 08:08
Hi @zouhangwithsweet 👋! Thanks for reporting this.

The problem is not the `wagmi` package itself, but it's a timeout on our end which we are currently working on. So basically, if it takes longer than 30 seconds to resolve the dependencies, we get a timeout and the installation fails. This is a problem for projects with a bigger dependency tree.

Currently, the solution is to generate the `package-lock.json` locally and copy that file to your StackBlitz project. If we detect a `package-lock.json`, we can skip the resolution step and directly start installing dependencies.

I did this for you already to test it out and it works https://stackblitz.com/edit/vitejs-vite-jtqhsc.

I'm closing this issue because it's something we're currently working on and because there's a workaround (which is not ideal off course).

**Closed by SamVerschueren** 2022-05-25 08:08 UTC

**Comment by zouhangwithsweet** [comment] 2022-05-25 08:19
Thanks very much :)
