### ISSUE TITLE
Unable to fork

### ISSUE THREAD

**Issue by DmitryEfimenko** [stackblitz/webcontainer-core#529] opened 2022-01-11 05:06 UTC
### Describe the bug

Unable to fork an Angular app.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/form-field-error-example.ts

### Steps to reproduce

1. Go to https://material.angular.io/components/form-field/overview#error-messages
2. Open the StackBlitz example for "Form field with error messages" demo
3. Attempt to fork it
4. Observe the fork button to start spinning infinitely.
5. The console seems to report a 500 error

### Expected behavior

I should be able to fork a project

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 112298920,
  "usedJSHeapSize": 104070140,
  "jsHeapSizeLimit": 4294705152
}
Hash = 528f704493b63b14b6f9ee36935eead8382e8395
```

### Additional context

Upon clicking "Fork", I see a network request POST /api/projects failing with a 500 status code right away

**Comment by HeyGarrison** [comment] 2022-02-21 03:02
duplicate of #569 - we just shipped a fix for this too ❤️

**Closed by HeyGarrison** 2022-02-21 03:02 UTC
