### ISSUE TITLE
Can't edit github project without master branch

### ISSUE THREAD

**Issue by lexugowashere** [stackblitz/webcontainer-core#219] opened 2021-06-29 16:05 UTC
**Describe the bug:**
When connecting a project to an existing GitHub repo without a `master` branch, the error: Could not resolve reference "refs/heads/master" appears and the project seems to load forever.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/github-ctd7ra

**Steps to reproduce:**

1. Open project linked to a GitHub repo without a master `master` branch

**Expected behavior:**
Should load the default branch, or load the different branches and give the option to switch

**Version of webcontainer:**
Hash: 70a1ff62a0f0131ac0df3c30faf487fef744ac90

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.124
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 85395530,
  "usedJSHeapSize": 67277294,
  "jsHeapSizeLimit": 2172649472
}
```

**Comment by tony19** [comment] 2021-06-30 06:49
Looks like a duplicate of #195

**Comment by jrvidal** [comment] 2023-03-03 10:52
Duplicate of #195 alright

**Closed by jrvidal** 2023-03-03 10:52 UTC
Labels: git
