### ISSUE TITLE
No git binary found in $PATH

### ISSUE THREAD

**Issue by ellucianBret** [stackblitz/webcontainer-core#306] opened 2021-08-21 14:08 UTC
### Describe the bug

I opened a GitHub repository that has a node project with a package.json dependency to another GitHub repo. ```npm install``` fails with "No git binary found in $PATH".

The dependency is:
"@ellucian/experience-extension-hooks": "github:ellucian-developer/experience-extension-hooks#1.0.0"

Should get retrieval of dependencies work?

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-tbsfqm?file=package.json

### Steps to reproduce

1. go to https://stackblitz.com/github/ellucian-developer/experience-productivity-extensions
2. See the error in the Terminal.

### Expected behavior

npm install should be able to install GitHub dependencies.

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.159
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 124986694,
  "usedJSHeapSize": 114631214,
  "jsHeapSizeLimit": 4294705152
}
Hash = 8ffc536d8181e8b30c228dec423d18afae547c40
```

**Comment by SamVerschueren** [comment] 2021-08-23 14:48
Duplicate of #144.

We're working on an improved git experience which will also come with a git binary. Can't give you an estimate though. 🙏

**Closed by SamVerschueren** 2021-08-23 14:48 UTC
