### ISSUE TITLE
page not loading after saving to github

### ISSUE THREAD

**Issue by ghost** [stackblitz/webcontainer-core#461] opened 2021-12-04 02:54 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/38000441/144694285-8b14a7b9-fb04-4417-9687-804c42f94327.png)

### Link to the blitz that caused the error

https://stackblitz.com/edit/nextjs-dmotst

### Steps to reproduce

https://stackblitz.com/edit/nextjs-dmotst

### Expected behavior

the page needs to load so that i can work on the project

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 56851657,
  "usedJSHeapSize": 51654097,
  "jsHeapSizeLimit": 820248576
}
Hash = 6c82f838340a5d37c50f004ca724bcc8f75bc71c
```

### Additional context

until the github save was made there was no issue with opening the next.js project in chrome tab and in stackblitz application

**Comment by JANSON-JOHN** [comment] 2021-12-06 02:44
Also check this link for another issue that occured during the creation of this project 
https://github.com/vercel/next.js/discussions/32051

**Comment by d3lm** [comment] 2021-12-06 08:17
Hey there! Can you please provide more information, e.g. proper description of the issue and steps to reproduce. Opening the link works just fine for me.

**Comment by JANSON-JOHN** [comment] 2021-12-06 11:57
I have shared some pics of the issue in my g drive( https://drive.google.com/drive/folders/15SPCAa-l58LLJndPpgOjrXX-KnWXQawD?usp=sharing  ).The pics with name 1 represent the state before the issue and those with 2 represent those after the issue has occured . When I try to open the project ( https://stackblitz.com/edit/nextjs-dmotst  ), in the stackblitz app or Chrome, nothing is displayed in the screen initially before the page loads. 

The issue occured  after I saved the project to Github . Till then, there was no issue with the project.

I cannot even edit the project anymore as the error occurs within 2 to 3 seconds of opening the project in chrome or stackblitz app. Please tell if any more specific info is needed.

**Comment by d3lm** [comment] 2021-12-06 12:18
Ok thanks! Do you have a clear list of steps to reproduce this issue?

**Comment by JANSON-JOHN** [comment] 2021-12-06 12:59
Yes for me to reproduce the issue the steps are 
1 Open the project ( https://stackblitz.com/edit/nextjs-dmotst ), in the stackblitz app or Chrome,

Not sure if it is a chrme issue since you said it works for you. One request is could you please try to  save the project to github and give me a link to the repo since the repo for this project does not show any files for me as you can see below

![image](https://user-images.githubusercontent.com/38000441/144850304-733093cc-cb15-453a-9977-5dd57f98de3e.png)

**Comment by JANSON-JOHN** [comment] 2021-12-06 17:12
1. I created another github repo( https://github.com/JANSON-JOHN/Nextjs-1-bug-chk-2  ) and tried to upload all files of this repo so as to check if the issue is with this repo only  and got another error as shown below. Hope this helps

![image](https://user-images.githubusercontent.com/38000441/144890778-ab881722-beda-49ee-bc1b-66d6257207cb.png)

**Comment by d3lm** [comment] 2023-02-22 14:21
I am going to close this issue because there hasn't been any activity in a while, and the repository nor project on StackBlitz still exist which makes it hard to reproduce the issue. If you think there's still a problem please open a new issue.

**Closed by d3lm** 2023-02-22 14:21 UTC
Labels: git
