### ISSUE TITLE
BUG: Installed dependencies don't show up in package.json

### ISSUE THREAD

**Issue by mehulbaid** [stackblitz/webcontainer-core#110] opened 2021-05-28 02:11 UTC
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-jhjbv3?file=package.json

**Steps to reproduce:**

1. open package.json
2. edit something (example: description) and save
3. then, do `npm i @hapi/hapi`
4. see the dependency not getting updated in package.json.

**Expected behavior:**
The Dependency should be getting updated in package.json.

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots:**
![image](https://user-images.githubusercontent.com/27810481/119919462-214bb800-bf88-11eb-9b95-2dc71700567f.png)

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 57965435,
  "usedJSHeapSize": 54503299,
  "jsHeapSizeLimit": 4294705152
}

**Comment by KwintenP** [comment] 2021-05-28 11:46
This is a bug indeed!

🙏 for reporting.

**Comment by mehulbaid** [comment] 2021-08-11 23:30
any updates on this?

**Comment by jrvidal** [comment] 2021-09-15 12:51
@mehulbaid I'm having trouble reproducing from your link, since it already includes `@hapi/hapi`. This might be related to https://github.com/stackblitz/webcontainer-core/issues/102, which I cannot reproduce either. Are you still observing this issue?

**Comment by mehulbaid** [comment] 2021-09-22 10:49
it includes @hapi/hapi but the same isn't reflected in package.json and gives out an error about module not found when imported.

**Comment by jrvidal** [comment] 2021-09-22 11:39
@mehulbaid Are the "Steps to reproduce" you gave above still accurate? Should I start from the blitz you linked?

**Comment by mehulbaid** [comment] 2021-10-05 09:43
@jrvidal yes, they are still valid.

**Comment by jrvidal** [comment] 2021-10-05 15:18
@mehulbaid Sorry but we don't have enough info to act on this. I can't reproduce with the steps and the blitz given above. The blitz, as mentioned before, does include `@hapi/hapi` in its `package.json`, maybe b/c it was last saved _after_ trying to make the installation work.

If you are still observing this, could you post a gif and/or screenshots of the browser console? Something that could be helpful is to give reproduction steps as an anonymous user (e.g. "enter this blitz as anon and for kit, then..."), to be sure we can repro the bug after forking your blitz. Anything that helps us [reproducing](https://stackoverflow.com/help/minimal-reproducible-example) the issue.

**Comment by jrvidal** [comment] 2021-12-10 14:51
@mehulbaid Closing this as we don't have enough actionable info. Please feel free to open a new issue if you run into trouble. Thanks!

**Closed by jrvidal** 2021-12-10 14:51 UTC
Labels: tracked, needs more info
