### ISSUE TITLE
BUG: project with `"type": "module"` not working correctly

### ISSUE THREAD

**Issue by ghoullier** [stackblitz/webcontainer-core#32] opened 2021-05-21 07:15 UTC
---
name: Bug report
about: Create a report to help us improve
title: 'project with `"type": "module"` not working'
labels: 'esm'
assignees: ''

---

**Describe the bug**
If you add the entry `"type": "module"` on `package.json` break the normal behavior

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-wyhu7f?file=package.json

**To Reproduce**
1. run node `index.js`

**Expected behavior**
A message is this display with : `Hello Node.js v14.16.0!`

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**
![Capture d’écran 2021-05-21 à 09 15 11](https://user-images.githubusercontent.com/2315749/119097476-0e2f6a00-ba15-11eb-8b43-feb31d07b90e.png)

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 63981338,
  usedJSHeapSize: 59038818,
  jsHeapSizeLimit: 4294705152
}

**Additional context**

**Comment by SamVerschueren** [comment] 2021-05-21 07:37
Thanks for reaching out @ghoullier! Currently ESM is not yet supported unfortunately. But the future is bright https://twitter.com/jdalton/status/1395510624830988290 :).

**Comment by ghoullier** [comment] 2021-05-21 07:48
🙏 Thanks for your reply

**Comment by KwintenP** [comment] 2021-05-21 08:10
Closing as duplicate of #6

**Closed by KwintenP** 2021-05-21 08:10 UTC
Labels: enhancement
