### ISSUE TITLE
Nextjs v13 Installing Dependencies Failed

### ISSUE THREAD

**Issue by dhavalveerarediff** [stackblitz/webcontainer-core#912] opened 2022-12-01 07:30 UTC
### Describe the bug

Hello,

I am creating a Nextjs Project from scratch which has the Nextjs version v13 which is failing to Install the Dependencies, please look into this matter.

I'm building the Project in Nextjs v13 from scratch in my local system where it's working perfectly fine but StackBlitz have some issue for installing the dependencies.

### Link to the blitz that caused the error

https://stackblitz.com/edit/nextjs-pmcz3s?file=package.json

### Steps to reproduce

there's no steps to reproduce

### Expected behavior

The expected behavior is to install the dependencies properly & run the start command to run the Nextjs App

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 85975618,
  "usedJSHeapSize": 77458466,
  "jsHeapSizeLimit": 4294705152
}
Hash = 0478c85eccde42845cdffe4745a763e1f3cb6e82
```

**Comment by d3lm** [comment] 2022-12-16 19:09
Hey there 👋 Thanks for the bug report, but the link you provided doesn't work for me. I am getting a 404. Can you please provide a working link and add some more information as to what the issue is with a list of steps to reproduce?

**Comment by dhavalveerarediff** [comment] 2022-12-17 02:36
> Hey there 👋 Thanks for the bug report, but the link you provided doesn't work for me. I am getting a 404. Can you please provide a working link and add some more information as to what the issue is with a list of steps to reproduce?

https://stackblitz.com/edit/nextjs-jb2zpq?file=package.json

**Comment by SamVerschueren** [comment] 2022-12-22 06:58
Hi @dhavalveerarediff! We found out that the latest release (next@13.0.7) is broken on WebContainer. Version 13.0.6 still works. We will have to look into why that is. In the mean time, we made sure that our starter project that you can create from the dashboard is updated to pull in a working version (13.0.6).

**Comment by dhavalveerarediff** [comment] 2022-12-25 10:54
@SamVerschueren @d3lm , please look at the attached image, now this way StackBlitz is crashing the page, and the Project URL => [StackBlitz Project](https://stackblitz.com/edit/nextjs-hs1ys1?file=pages%2Findex.js)


![image](https://user-images.githubusercontent.com/81204733/209465176-682f61bf-64ab-43a1-b51b-41bf686ea1cb.png)

**Comment by dhavalveerarediff** [comment] 2022-12-25 10:55
@SamVerschueren @d3lm = looks like currently StackBlitz doesn't have a stable Code particularly for Nextjs v13

**Comment by SamVerschueren** [comment] 2023-03-08 13:11
Hi @dhavalveerarediff . The `SBOX_FATAL_MEMORY_EXCEEDED` error is because Chrome runs out of memory. This could happen if you have quite some Chrome tabs open, and maybe also quite some StackBlitz projects? The [link that you shared](https://stackblitz.com/edit/nextjs-hs1ys1?file=pages%2Findex.js) does seem to work for me.

We found the issue with Next.js and tracking this internally.

**Comment by SamVerschueren** [comment] 2023-03-08 13:14
I was too fast with answering. We did fix this for the latest Next.js versions. So it also works with the latest version https://stackblitz.com/edit/nextjs-vjwqlx. Closing this issue.

**Closed by SamVerschueren** 2023-03-08 13:14 UTC
Labels: tracked
