### ISSUE TITLE
use spawn to cd the inner directory , then use ls , the files are still in the root directory.

### ISSUE THREAD

**Issue by strugglinglee** [stackblitz/webcontainer-core#1052] opened 2023-04-29 03:51 UTC
### Describe the bug

hello, the bug is about @webcontainer/api.

using by webcontainerInstance.spawn, after cd , I want to see the files in inner directory， but I got the files in the root

### Link to the blitz that caused the error

https://stackblitz.com/edit/cd-test-hi

### Steps to reproduce

https://stackblitz.com/edit/cd-test-hi

1. you can see my operation in main.js.
2. use webcontainerInstance.spawn('cd', [path])  into inner directory
3. use webcontainerInstance.spawn('ls') to look up files, the results is still about the root directory
4. you can see it very clearly from my test project

### Expected behavior

I want to use @webcontainer/api to see the content about the inner directory

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by d3lm** [comment] 2023-05-02 11:56
Hey 👋 Thanks for the report. That is by design. If you run separate processes the `cwd` won't be changed once you run `cd xxx` for subsequent processes. If you wish to do that, you could spawn a shell `/bin/jsh`, and then send `cwd xxx` (via stdin) which will change the working directory of the current shell. You can then send other commands like `ls` and it will use whatever working dir is currently set. There is currently no API to change the working dir globally so that independent processes will all use that working dir.

**Comment by jrvidal** [comment] 2023-07-03 08:49
Closing this for now as it is not a bug as far as we can see. Thanks for the report and please feel free to open a new issue if needed.

**Closed by jrvidal** 2023-07-03 08:49 UTC
