### ISSUE TITLE
A new https://vite.new/vue project gets created with an "_gitignore" instead of ".gitignore"

### ISSUE THREAD

**Issue by segevfiner** [stackblitz/webcontainer-core#697] opened 2022-05-17 00:15 UTC
### Describe the bug

A new https://vite.new/vue project gets created with an "_gitignore" instead of ".gitignore"

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-a5gxnw?file=src/App.vue

### Steps to reproduce

1. Go to https://vite.new/vue
2. The new project gets created with a "_gitignore" instead of ".gitignore".

### Expected behavior

It gets created with a".gitignore"

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 101.0.4951.64
Major version = 101
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 78901271,
  "usedJSHeapSize": 59250547,
  "jsHeapSizeLimit": 4294705152
}
Hash = 5428dc6786c976e0e08fde1105586a722833c4ef
```

**Comment by tony19** [comment] 2022-05-17 02:26
Duplicate of #526

**Closed** 2022-05-17 04:15 UTC
