### ISSUE TITLE
Not able to connect to github

### ISSUE THREAD

**Issue by AmitKSwain** [stackblitz/webcontainer-core#433] opened 2021-11-26 07:12 UTC
### Describe the bug

Stack blitz is not able to connect to my git repo .
The spinner keeps spinning .
At the beginning I see an error "Buffer not defined ."
This error is not in my code because this is running in Heroku environment and in my local and I am not using Buffer. 

### Link to the blitz that caused the error

https://stackblitz.com/edit/rrp-web-api

### Steps to reproduce

- Open the stack blitz open a project connected to git repo
- Do some code change 
- Try to commit 

### Expected behavior

The spinner near git repo symbol keeps spinning 
Commit button is not enabled even after code change 

### Screenshots

![image](https://user-images.githubusercontent.com/30809766/143541104-86d21473-97ed-441f-a803-770c6c0d7381.png)
![image](https://user-images.githubusercontent.com/30809766/143541247-2d6b415e-192a-476f-bbc7-209a4eb4183d.png)

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 71024914,
  "usedJSHeapSize": 66603674,
  "jsHeapSizeLimit": 4294705152
}
Hash = f0f0e35d34e6f38828752db79b041c48b98806b5
```

**Comment by tony19** [comment] 2021-11-27 17:51
Duplicate of #431

**Comment by ElMassimo** [comment] 2022-03-24 13:45
Running into a different error that prevents connecting to GitHub:


<img width="1062" alt="Screen Shot 2022-03-24 at 10 44 57" src="https://user-images.githubusercontent.com/1158253/159929693-939e682a-87f7-45e9-a520-080ee0670a0f.png">

```
gitworker-e9c1e20e6208.js:2
StackblitzFsGit addAll err ResolveRefError: Could not resolve reference "refs/heads/master".
    at Function.resolve (gitworker-e9c1e20e6208.js:2:176948)
    at async gitworker-e9c1e20e6208.js:2:200082
    at async he.readdir (gitworker-e9c1e20e6208.js:2:200526)
    at async Promise.all (/edit/index 0)
    at async l (gitworker-e9c1e20e6208.js:2:202875)
    at async f (gitworker-e9c1e20e6208.js:2:203105)
    at async ar (gitworker-e9c1e20e6208.js:2:235004)
    at async Object.addAll (gitworker-e9c1e20e6208.js:2:245818)
(anonymous) @ gitworker-e9c1e20e6208.js:2
Promise.catch (async)
addAll @ gitworker-e9c1e20e6208.js:2
addAll @ gitworker-e9c1e20e6208.js:2
e.onCall @ index.js:61
(anonymous) @ index.js:16

gitworker-e9c1e20e6208.js:2
StackblitzFsGit statusList err ResolveRefError: Could not resolve reference "refs/heads/master".
    at Function.resolve (gitworker-e9c1e20e6208.js:2:176948)
    at async gitworker-e9c1e20e6208.js:2:200082
    at async he.readdir (gitworker-e9c1e20e6208.js:2:200526)
    at async Promise.all (/edit/index 0)
    at async l (gitworker-e9c1e20e6208.js:2:202875)
    at async f (gitworker-e9c1e20e6208.js:2:203105)
    at async ar (gitworker-e9c1e20e6208.js:2:235004)
    at async ur.statusList (gitworker-e9c1e20e6208.js:2:237735)
    at async Object.statusList (gitworker-e9c1e20e6208.js:2:245942)
```

**Closed** 2023-03-03 10:46 UTC
Labels: git
