### ISSUE TITLE
Failed at running the start command

### ISSUE THREAD

**Issue by MommaRoo37** [stackblitz/webcontainer-core#726] opened 2022-06-21 13:06 UTC
### Describe the bug

Beginner here.  Appears when selecting the link https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts  from the angular.io/start.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts

### Steps to reproduce

1) click link on angular.io/start 
2) stackblitz opens new window and attempts to launch
3) failure when running the start command (last step).

### Expected behavior

expected to start

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/63913530/174805832-03282171-d1b0-49b0-82c8-e680081e339a.png)

### Platform

```
Browser name  = Chrome
Full version  = 102.0.0.0
Major version = 102
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 173414850,
  "usedJSHeapSize": 160808238,
  "jsHeapSizeLimit": 4294705152
}
Hash = bbb482e7415e406cfc62838751ca694c1dc24cf6
```

**Comment by SamVerschueren** [comment] 2022-06-21 13:15
Duplicate of #724

**Closed by SamVerschueren** 2022-06-21 13:15 UTC
