### ISSUE TITLE
JWT libraries  `jose` and `jsonwebtoken` fail in WebContainers

### ISSUE THREAD

**Issue by FossPrime** [stackblitz/webcontainer-core#999] opened 2023-03-14 02:45 UTC
### Describe the bug

This JWT signing code returns an Unsupported error https://stackblitz.com/edit/jose-stackblitz-bug?file=package.json,index.js
But it runs on Runkit, local, bun and Browsers! https://runkit.com/hesygolu/640fd42ef60e0c000883aab1

I was trying to switch to Jose after Auth0's jsonwebtoken v9 stopped working on StackBlitz. Jose has worked very hard to make the module work on browsers, unlike Auth0's version.

Is there a way to expose the browser's crypto module to WebContainers, fixing Jose's browser code?

### Link to the blitz that caused the error

- https://stackblitz.com/edit/jose-stackblitz-bug?file=package.json,index.js
- bare metal repro: https://stackblitz.com/edit/node-2hjdkz?file=index.js,package.json

### Steps to reproduce

Try to sign a JWT using jose (works in Node, Bun and Browsers) or Auth0's jsonwebtoken

### Expected behavior

Modules with browser code declared should always work.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: Linux
- Browser: ChromeOS
- Version: 111

**Comment by panva** [comment] 2023-03-14 19:51
https://github.com/panva/jose/issues/517#issuecomment-1467540208

**Comment by d3lm** [comment] 2023-07-14 19:18
Hey there 👋 I am closing this issue because it's been fixed. If you re-run the provided reproduction the access token gets printed in the terminal.

**Closed by d3lm** 2023-07-14 19:18 UTC
Labels: tracked
