### ISSUE TITLE
Nuxt beta doesn't work

### ISSUE THREAD

**Issue by alekrudolph** [stackblitz/webcontainer-core#359] opened 2021-10-21 20:48 UTC
### Describe the bug

See for yourself. The "preview" just spins forever, even though the terminal says it is listening to port 3000.

### Link to the blitz that caused the error

https://stackblitz.com/edit/nuxt-starter-djtmef?file=md!README.md

### Steps to reproduce

1. Go to my blitz

### Expected behavior

Website loads, "browser" refresh button is not disabled

### Screenshots

![image](https://user-images.githubusercontent.com/92952858/138354317-4d6d0f19-db39-4303-a675-e6ff7a809613.png)

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.81
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 115755956,
  "usedJSHeapSize": 108455116,
  "jsHeapSizeLimit": 2172649472
}
Hash = 88a7151d177878d00bf438b30e057ed5805fdcd2
```

**Comment by jrvidal** [comment] 2021-10-22 02:35
@alekrudolph I can't reproduce the issue :disappointed: Do you see any errors in the console?

![Screenshot from 2021-10-22 04-34-27](https://user-images.githubusercontent.com/1636604/138384056-771d7751-149e-4865-a55c-40193ad65fd0.png)

**Comment by tony19** [comment] 2021-10-22 03:30
I can reproduce the problem in Chrome's Incognito mode, and no relevant logs appear in the console. In Chrome's normal mode, the preview window opens to a blank screen after the dev server starts up, and I have to hit the preview pane's refresh button to get the site to appear. Both behvaiors are consistently reproducible for me.

```
OS: macOS 11.2.3
Chrome: 95.0.4638.54
```

**Comment by jrvidal** [comment] 2022-01-20 22:33
We have a better UI for ServiceWorker errors, so I'm closing this. Please feel free to open a new issue if you find anything else not working properly.

Thanks for the report!

**Closed by jrvidal** 2022-01-20 22:33 UTC
Labels: needs more info
