### ISSUE TITLE
Starting new Astro-Blog template, says "upgrade required"

### ISSUE THREAD

**Issue by Seanmclem** [stackblitz/webcontainer-core#403] opened 2021-11-14 14:50 UTC
### Describe the bug

New Astro-Blog-node web container
generates `Failed to load resource: the server responded with a status of 426 (Upgrade Required)`
when started for the first time

https://stackblitz.com/edit/snowpackjs-astro-4pg2fv?file=README.md

### Link to the blitz that caused the error

https://stackblitz.com/edit/snowpackjs-astro-4pg2fv

### Steps to reproduce

open and run

### Expected behavior

should start

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.162
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 13982.88.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.162 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87214151,
  "usedJSHeapSize": 79532367,
  "jsHeapSizeLimit": 2040528896
}
Hash = 320dd3b483ec8295ca1e4a3ccd95cf9e5165f9d0
```

**Comment by tony19** [comment] 2021-11-14 20:39
Duplicate of #341 

See https://github.com/stackblitz/webcontainer-core/issues/341#issuecomment-936290408

**Closed** 2021-11-15 00:22 UTC
