### ISSUE TITLE
forking broken

### ISSUE THREAD

**Issue by daniel-sc** [stackblitz/webcontainer-core#570] opened 2022-01-25 12:23 UTC
### Describe the bug

when clicking "fork" the spinner load forever, but nothing happens.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/breadcrumb-custom-root-example.ts

### Steps to reproduce

1. go to https://stackblitz.com/run?file=src/app/breadcrumb-custom-root-example.ts
2. click "fork"

### Expected behavior

it should create a fork

### Parity with Local

- [X] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/117919/150976353-bd8163ca-c33a-4253-920e-4c59790785a7.png)

### Platform

```
Browser name  = Chrome 
Full version  = 97.0.4692.99
Major version = 97
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 70202393,
  "usedJSHeapSize": 64069493,
  "jsHeapSizeLimit": 4294705152
}
Hash = 5df97b5e61f923919ea927c406a4806b792de8c6
```

**Comment by daniel-sc** [comment] 2022-01-25 12:24
probably a duplicate of #569

**Comment by HeyGarrison** [comment] 2022-02-21 02:52
Closing b/c duplicate of #569

**Closed by HeyGarrison** 2022-02-21 02:52 UTC
