### ISSUE TITLE
Intellisense doesn't show suggestions for standard Node.js modules

### ISSUE THREAD

**Issue by angry-meow** [stackblitz/webcontainer-core#1078] opened 2023-05-21 15:23 UTC
### Describe the bug

![изображение](https://github.com/stackblitz/webcontainer-core/assets/31481176/f09b47ec-7e0a-44bf-87d6-53218947e759)

### Link to the blitz that caused the error

https://stackblitz.com/edit/bug-vn9bmo?file=index.mjs

### Steps to reproduce

1. Go to https://stackblitz.com/edit/bug-vn9bmo?file=index.mjs
2. Place the cursor after `fs.`
3. Press Ctrl+Space
4. You can see the `No suggestions.` message

### Expected behavior

Proper suggestions are visible.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

Current:

![изображение](https://github.com/stackblitz/webcontainer-core/assets/31481176/a574ba72-ce48-496c-9555-c30e8e7278f6)

Expected (VS Code):

![изображение](https://github.com/stackblitz/webcontainer-core/assets/31481176/65b44c09-3ac7-4624-9028-bb10ad68205b)

### Platform

- OS: Windows 11
- Browser: Firefox
- Version: 113.0.1 (64-bit)

**Comment by stackblitz-test2** [comment] 2023-05-22 09:17
Hi,

Node itself doesn't ship TypeScript types, so I believe this is expected behavior.

You can install community-maintained TypeScript types for Node with:

```sh
npm install -D @types/node
```

**Comment by fvsch** [comment] 2023-05-25 12:50
Hi,

Node itself doesn't ship TypeScript types, so I believe this is expected behavior.

You can install community-maintained TypeScript types for Node with:

```sh
npm install -D @types/node
```

**Comment by SamVerschueren** [comment] 2023-06-12 14:52
Closing this because the answer from @fvsch is correct.

**Closed by SamVerschueren** 2023-06-12 14:52 UTC
