### ISSUE TITLE
Unable for running npm test in angular

### ISSUE THREAD

**Issue by WilmerGuerrero** [stackblitz/webcontainer-core#595] opened 2022-02-15 14:21 UTC
### Describe the bug

I was trying to run some tests with Karma but it threw an exception in the terminal:

An unhandled exception occurred: ENOENT: no such file or directory, lstat '/home/projects/node-ceo43j/src/styles.css'
See "/tmp/ng-3oYOOa/angular-errors.log" for further details.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-ceo43j?file=src%2Fapp%2Fheroes%2Fheroes.component.deep.spec.ts

### Steps to reproduce

1. Write on the project some tests in .spec files.
2. run npm test

### Expected behavior

Be able to run the Karma tests

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

![stackblitz error](https://user-images.githubusercontent.com/52579232/154080636-cbf12579-a2e6-493f-a7bf-3a78e588dd5e.jpg)

### Platform

```
Browser name  = Chrome
Full version  = 98.0.4758.80
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.50
performance.memory = {
  "totalJSHeapSize": 117393537,
  "usedJSHeapSize": 107556557,
  "jsHeapSizeLimit": 4294705152
}
Hash = e1937cc6e2ee7e7a1da198d43493f4063378a564
```

**Comment by d3lm** [comment] 2022-02-18 11:00
Hi there 👋 

The problem is that the `src/styles.css` does indeed not exist, so the error you're seeing is correct. I am closing this issue but feel free to open a new issue if you run into more issues.

**Closed by d3lm** 2022-02-18 11:00 UTC
