### ISSUE TITLE
Several issues for React typescript blank project

### ISSUE THREAD

**Issue by pashvin** [stackblitz/webcontainer-core#1477] opened 2024-06-29 19:41 UTC
### Describe the bug

1. JSX gets a warning "Cannot use JSX unless the '--jsx' flag is provided"
2. IntelliSense does not work. If I take out React import, then it works

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-ewz2w4?file=src%2FApp.tsx,src%2Fmain.tsx

### Steps to reproduce

Just create a blank React type script project and you will see both issues

### Expected behavior

No error and react IntelliSense should work

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 126.0.0.0
Major version = 126
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 103340579,
  "usedJSHeapSize": 99537707,
  "jsHeapSizeLimit": 4294705152
}
Hash = 70dbe416
```

**Comment by alexiz10** [comment] 2024-07-01 23:46
I am also experiencing this while using Firefox.

**Comment by namuol** [comment] 2024-07-03 23:16
Partial duplicate of #1465

**Comment by empz** [comment] 2024-07-06 09:57
I honestly can't believe how this doesn't work out of the box. Between this and the issue with Next.js app not being able to run because of the SWC compiler... Come on team, 95% of people using SB are going to be either using the React or the Next.js templates. They should work out of the box.

**Comment by SamVerschueren** [comment] 2024-07-15 06:54
Closing this in favour of #1465.

> We are aware of this issue and we have a fix for it. I will try to get it released today.

It wasn't an easy fix so it took a bit to address it. Sorry for the inconvenience.

**Closed by SamVerschueren** 2024-07-15 06:54 UTC
