### ISSUE TITLE
it does not load

### ISSUE THREAD

**Issue by TheAnvils** [stackblitz/webcontainer-core#193] opened 2021-06-15 15:14 UTC
It has been loading for 20 minutes and it is still not loaded.

**Comment by SamVerschueren** [comment] 2021-06-15 15:18
Could you please fill in the required information? It helps us identify the issue.

Like, what project are you opening? Is it a GitHub URL? Is it WebContainer trying to boot?

**Comment by TheAnvils** [comment] 2021-06-15 16:31
> Could you please fill in the required information? It helps us identify the issue.
> 
> Like, what project are you opening? Is it a GitHub URL? Is it WebContainer trying to boot?

I just made a new node project thing and the webcontainer won’t load

**Comment by TheAnvils** [comment] 2021-06-15 17:05
![Screenshot 2021-06-15 19 05 07](https://user-images.githubusercontent.com/79940840/122094597-a2ba9b80-ce0c-11eb-8f2a-e39e5380d28d.png)

**Comment by SamVerschueren** [comment] 2021-06-15 20:27
It is loaded. You now have full control over what you want to do. Run `node index.js` for instance.

If you want it to do something straight away, you can create a `.stackblitzrc` like this

```
{
    "startCommand": "node index.js"
}
```

Reload the website and it will auto start.

Closing the issue as it works as intended.

**Closed** 2021-06-15 20:27 UTC
Labels: needs more info
