### ISSUE TITLE
BUG: TypeError: Cannot read property 'constants' of undefined

### ISSUE THREAD

**Issue by hemanth** [stackblitz/webcontainer-core#152] opened 2021-06-05 00:07 UTC
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-huxnd7?file=server.js

**Steps to reproduce:**

```
❯ node index.js 
TypeError: Cannot read property 'constants' of undefined
    at Object.a0_0x2c98 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:983601)
    at _0x311907 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:8:22374)
    at Object.a0_0x2c98 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:948134)
    at _0x311907 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:8:22374)
    at Object.a0_0x2c98 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:1632165)
    at _0x311907 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:8:22374)
❯ node index.js 
TypeError: Cannot read property 'constants' of undefined
    at Object.a0_0x2c98 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:983601)
    at _0x311907 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:8:22374)
    at Object.a0_0x2c98 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:948134)
    at _0x311907 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:8:22374)
    at Object.a0_0x2c98 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:1632165)
    at _0x311907 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:8:22374)
    at _0x77a0cc (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:11:163505)
    at https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:11:49780
    at NativeModule.compileForInternalLoader (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:305385)
    at NativeModule.compileForPublicLoader (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:304509)

~/projects/node-huxnd7
❯ node server.js 
TypeError: Cannot read property 'constants' of undefined
    at Object.a0_0x2c98 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:983601)
    at _0x311907 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:8:22374)
    at Object.a0_0x2c98 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:948134)
    at _0x311907 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:8:22374)
    at Object.a0_0x2c98 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:1632165)
    at _0x311907 (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:8:22374)
    at _0x77a0cc (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:11:163505)
    at https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:11:49780
    at NativeModule.compileForInternalLoader (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:305385)
    at NativeModule.compileForPublicLoader (https://node-huxnd7.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:304509)
```

**Expected behavior:**
Server should have started 

**Version of webcontainer:**
Hash: cb1eb6b301af424e8dffb694972509f06ea6b5db

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 101784650,
  "usedJSHeapSize": 91009210,
  "jsHeapSizeLimit": 4294705152
}

**Additional context:**

**Comment by SamVerschueren** [comment] 2021-06-05 11:40
Hi @hemanth! Thanks for trying it out and for reporting any issues you run into. I believe this doesn't work because we lack support for HTTP/2 right now. Is that correct @d3lm?

**Comment by d3lm** [comment] 2021-06-17 15:34
Yes that's correct. Right now we don't support http2 but it's on our roadmap to fully support it at some point.

**Comment by jrvidal** [comment] 2021-10-08 12:08
Closing as duplicate of https://github.com/stackblitz/webcontainer-core/issues/126

**Closed by jrvidal** 2021-10-08 12:08 UTC
Labels: core
