### ISSUE TITLE
Remix redirect doesn't redirect client

### ISSUE THREAD

**Issue by HeyGarrison** [stackblitz/webcontainer-core#713] opened 2022-06-09 12:54 UTC
### Describe the bug

In the example below, if you submit to the /bug route the action is called and returns a redirect response, but the user is never actually redirected. Doesn't work in either in iframe pseudo browser or a separate window. This all works as expected with a new local remix install, so it doesn't appear to be remix.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-ianhzk?file=app%2Froutes%2Fbug.tsx,app%2Froutes%2Findex.tsx

### Steps to reproduce

1. Let project load
2. Click "go to the bug"
3. Submit the form
4. Observe the error

### Expected behavior

Form should submit properly and redirect the user.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by jacob-ebey** [comment] 2022-06-17 03:08
This can be distilled down even further without a form submission and just a link click that ultimately makes a fetch and returns a "redirect". FYI, these aren't "real" redirects, they are 204 responses with a `"X-Remix-Redirect"` header instead of a `Location` to work around browser limitations.

**Comment by mrkiffie** [comment] 2022-06-17 07:40
I too have encountered the same issue with `redirect` not working as expected with the `POST` is handled with javascript. 

- If I disable javascript and let the browser submit, the redirect works.
- If I add `reloadDocument` on the `<Form />`, the redirect works.
- It works as expected locally on node v16.

I've created by own reproduction of the issue before I saw this issue.

The `POST` request gets stuck in the `pending` state and eventually times out after 5 minutes.

https://stackblitz.com/edit/node-8mnuma?file=app%2Froutes%2Findex.tsx,app%2Froutes%2Ftest%2Fform.tsx,app%2Froutes%2Ftest%2F%24testId.tsx

I was using Chrome 102.0.5005.61 on macOS Monterey.

I'm wondering if the issue is related to the 204 status that Remix uses when redirecting without doing a full page reload where it would use 302 by default. I'm not sure if the issue is in the service worker or the "server" context. I'm not yet familiar with how these are connected.

I'll try step through the code this weekend to see if there is anything obvious that is causing this.

**Comment by Nemikolh** [comment] 2023-04-05 17:50
Hi everyone! :wave: Thank you so much for the reproduction links! 

I think this issue was fixed.

In every blitz shared, I can't seem to reproduce the issues reported. All redirect that should be happening are happening as expected. I'll close this issue but feel free to reopen if I missed something!

**Closed by Nemikolh** 2023-04-05 17:50 UTC
