### ISSUE TITLE
11ty based project fails to start

### ISSUE THREAD

**Issue by genemars** [stackblitz/webcontainer-core#602] opened 2022-02-21 15:19 UTC
### Describe the bug

I tried importing a project from github but it fails with the following error:

```
~/projects/rlmiarvgx.github
❯ npm start
$ npx @11ty/eleventy --serve
[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[11ty] > Error in your Eleventy config file '/home/projects/rlmiarvgx.github/.eleventy.js'.

`EleventyConfigError` was thrown
[11ty] > nodeNC failed:

`Error` was thrown:
[11ty]     Error: nodeNC failed:
    
    
        at sendMessage (/home/projects/rlmiarvgx.github/node_modules/sync-rpc/lib/index.js:154:11)
        at createClient (/home/projects/rlmiarvgx.github/node_modules/sync-rpc/lib/index.js:173:27)
        at Object.eval (/home/projects/rlmiarvgx.github/node_modules/sync-request/lib/index.js:16:14)
        at Object.function (https://rlmiarvgx--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:15:95453)
        at Module._compile (https://rlmiarvgx--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:190325)
        at Object.Module._extensions..js (https://rlmiarvgx--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:190684)
        at Module.load (https://rlmiarvgx--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:188760)
        at Function.Module._load (https://rlmiarvgx--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:186300)
        at Module.require (https://rlmiarvgx--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:189078)
        at i (https://rlmiarvgx--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:443011)

~/projects/rlmiarvgx.github
❯ node --version
v14.17.0
```

### Link to the blitz that caused the error

https://stackblitz.com/github/zuixjs/zuix-web-starter?terminal=start

### Steps to reproduce

1. enter the reported URL in your browser
2. error is thrown once the `npm start` command is issued

### Expected behavior

After `npm start` is issued, the web server should start listening.

### Parity with Local

- [X] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 98.0.4758.102
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 117376262,
  "usedJSHeapSize": 110430938,
  "jsHeapSizeLimit": 2172649472
}
Hash = d64d45524a435df425e7813603b52872ecfbe08e
```

**Comment by jrvidal** [comment] 2022-02-22 10:44
@genemars Thanks for the report. You project seems to include file dependencies:

```
"zuix-cli": "file:../zuix-cli",
```

which are not supported by [turbo](https://developer.stackblitz.com/docs/platform/turbo/), our package manager. I'll close this as a duplicate of https://github.com/stackblitz/webcontainer-core/issues/107, where we tracking progress of this feature.

**Comment by genemars** [comment] 2022-02-22 12:46
That was unintentionally pushed on a recent commit, but it's fixed now with the published package name, and the error is still there.
As you can see, it's related to some StackBlitz script unable to resolve `sync-request` dependency from `eleventy` package.

`** at Function.Module._resolveFilename (https://vbwipwyzo--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:188288)**`

In the original stacktrack in this post the error was diffent (`Error: nodeNC failed:`), I don't what changed now:

```
success Install finished in 3.173s
$ npx @11ty/eleventy --serve
[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[11ty] > Error in your Eleventy config file '/home/projects/vbwipwyzo.github/.eleventy.js'. You may need to run `npm install`.

`EleventyConfigError` was thrown
[11ty] > Cannot find module 'sync-request'
Require stack:
- /home/projects/vbwipwyzo.github/node_modules/zuix-cli/commands/compile-page.js
- /home/projects/vbwipwyzo.github/.eleventy.js
- /home/projects/vbwipwyzo.github/node_modules/@11ty/eleventy/src/TemplateConfig.js
- /home/projects/vbwipwyzo.github/node_modules/@11ty/eleventy/src/TemplateRender.js
- /home/projects/vbwipwyzo.github/node_modules/@11ty/eleventy/src/TemplateData.js
- /home/projects/vbwipwyzo.github/node_modules/@11ty/eleventy/src/Eleventy.js
- /home/projects/vbwipwyzo.github/node_modules/@11ty/eleventy/cmd.js

`Error` was thrown:
[11ty]     Error: Cannot find module 'sync-request'
    Require stack:
    - /home/projects/vbwipwyzo.github/node_modules/zuix-cli/commands/compile-page.js
    - /home/projects/vbwipwyzo.github/.eleventy.js
    - /home/projects/vbwipwyzo.github/node_modules/@11ty/eleventy/src/TemplateConfig.js
    - /home/projects/vbwipwyzo.github/node_modules/@11ty/eleventy/src/TemplateRender.js
    - /home/projects/vbwipwyzo.github/node_modules/@11ty/eleventy/src/TemplateData.js
    - /home/projects/vbwipwyzo.github/node_modules/@11ty/eleventy/src/Eleventy.js
    - /home/projects/vbwipwyzo.github/node_modules/@11ty/eleventy/cmd.js
        at Function.Module._resolveFilename (https://vbwipwyzo--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:188288)
        at Function.Module._load (https://vbwipwyzo--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:185865)
        at Module.require (https://vbwipwyzo--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:189078)
        at i (https://vbwipwyzo--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:443011)
        at _0x4248b4 (https://vbwipwyzo--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:15:95063)
        at Object.eval (/home/projects/vbwipwyzo.github/node_modules/zuix-cli/commands/compile-page.js:32:17)
        at Object.function (https://vbwipwyzo--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:15:95453)
        at Module._compile (https://vbwipwyzo--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:190325)
        at Object.Module._extensions..js (https://vbwipwyzo--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:190684)
        at Module.load (https://vbwipwyzo--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:188760)
```

**Comment by jrvidal** [comment] 2022-02-22 12:51
I can't run the blitz above on my local machine:
```
npx @11ty/eleventy --serve
[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[11ty] > Error in your Eleventy config file '/tmp/zuix/.eleventy.js'. You may need to run `npm install`.

`EleventyConfigError` was thrown
[11ty] > Cannot find module 'zuix-cli/commands/compile-page'
Require stack:
- /tmp/zuix/.eleventy.js
- /tmp/zuix/node_modules/@11ty/eleventy/src/TemplateConfig.js
- /tmp/zuix/node_modules/@11ty/eleventy/src/TemplateRender.js
- /tmp/zuix/node_modules/@11ty/eleventy/src/TemplateData.js
- /tmp/zuix/node_modules/@11ty/eleventy/src/Eleventy.js
- /tmp/zuix/node_modules/@11ty/eleventy/cmd.js

`Error` was thrown:
[11ty]     Error: Cannot find module 'zuix-cli/commands/compile-page'
    Require stack:
    - /tmp/zuix/.eleventy.js
    - /tmp/zuix/node_modules/@11ty/eleventy/src/TemplateConfig.js
    - /tmp/zuix/node_modules/@11ty/eleventy/src/TemplateRender.js
    - /tmp/zuix/node_modules/@11ty/eleventy/src/TemplateData.js
    - /tmp/zuix/node_modules/@11ty/eleventy/src/Eleventy.js
    - /tmp/zuix/node_modules/@11ty/eleventy/cmd.js
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
        at Function.Module._load (node:internal/modules/cjs/loader:778:27)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at Object.<anonymous> (/tmp/zuix/.eleventy.js:11:21)
        at Module._compile (node:internal/modules/cjs/loader:1101:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Comment by genemars** [comment] 2022-02-22 13:05
@jrvidal I am now trying downgrading `sync-request` that it's used in `zuix-cli` package, and see if this works.
I downgraded to `5.0.0` and now the error stacktrace is back to the original one I posted here:

```
Success Install finished in 9.122s
$ npx @11ty/eleventy --serve
[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[11ty] > Error in your Eleventy config file '/home/projects/gqaiqolvp.github/.eleventy.js'.

`EleventyConfigError` was thrown
[11ty] > nodeNC failed:

`Error` was thrown:
[11ty]     Error: nodeNC failed:
    
    
        at sendMessage (/home/projects/gqaiqolvp.github/node_modules/sync-rpc/lib/index.js:154:11)
        at createClient (/home/projects/gqaiqolvp.github/node_modules/sync-rpc/lib/index.js:173:27)
        at Object.eval (/home/projects/gqaiqolvp.github/node_modules/sync-request/lib/index.js:16:14)
        at Object.function (https://gqaiqolvp--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:15:95453)
        at Module._compile (https://gqaiqolvp--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:190325)
        at Object.Module._extensions..js (https://gqaiqolvp--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:190684)
        at Module.load (https://gqaiqolvp--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:188760)
        at Function.Module._load (https://gqaiqolvp--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:186300)
        at Module.require (https://gqaiqolvp--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:189078)
        at i (https://gqaiqolvp--github.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:443011)
```

I will go down to `4.x` and see what happen.

**Comment by genemars** [comment] 2022-02-22 13:20
@jrvidal downgrading `sync-request` to `4.0.3` in `zuix-cli` did the trick, it's up and running now.
Thanks.

**Closed** 2022-02-22 13:40 UTC
Labels: needs more info
