### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by anlachel** [stackblitz/webcontainer-core#393] opened 2021-11-10 14:15 UTC
### Describe the bug

The live example linked from this site (https://angular.io/guide/i18n-example) does not work.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Flocale%2Fmessages.fr.xlf

### Steps to reproduce

Just click on the link of the live Example. Nothing else.

### Expected behavior

App up and running

### Screenshots

$ ng serve
Locale data for 'baseHref' cannot be found.  No locale data will be included for this locale.
An unhandled exception occurred: Unsupported translation file format in /home/projects/fntgl3--run. The following parsers were tried:
*** ArbTranslationParser ***
*** SimpleJsonTranslationParser ***
WARNINGS:
 - File does not have .json extension.
*** Xliff1TranslationParser ***
*** Xliff2TranslationParser ***
*** XtbTranslationParser ***
WARNINGS:
 - Must have xtb or xmb extension.
See "/tmp/ng-J2wReA/angular-errors.log" for further details.

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 113484468,
  "usedJSHeapSize": 90656156,
  "jsHeapSizeLimit": 4294705152
}
Hash = d83b9b15484f32317787d8c7cc41da5651102bdc
```

### Additional context

Ang

**Comment by jrvidal** [comment] 2022-03-14 14:52
@anlachel This was, most likely, an error in the tutorial code. Do you still observe this issue?

**Comment by d3lm** [comment] 2023-02-22 13:55
I am going to close this issue because there hasn't been any activity for a long time and the issue is still missing more info. If you feel like there is still an issue, please file a new one.

**Closed by d3lm** 2023-02-22 13:55 UTC
Labels: needs more info
