### ISSUE TITLE
Preview isn't working in Brave Mobile

### ISSUE THREAD

**Issue by amalbenny** [stackblitz/webcontainer-core#585] opened 2022-02-06 16:46 UTC
### Describe the bug

Preview isn't supported chromium based browser Brave for mobile.
File: https://stackblitz.com/run?file=src/app/app.component.ts

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/app.component.ts

### Steps to reproduce

1. Use Brave for Android
2. Open file at https://stackblitz.com/run?file=src/app/app.component.ts
3. Click Preview

### Expected behavior

Preview should appear. But it shows error like - use chromium based browser like Brave and chrome

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Mobile Safari/537.36
performance.memory = {
  "totalJSHeapSize": 116000000,
  "usedJSHeapSize": 103000000,
  "jsHeapSizeLimit": 747000000
}
Hash = 5df97b5e61f923919ea927c406a4806b792de8c6
```

**Comment by jrvidal** [comment] 2022-02-09 10:47
Most likely a duplicate of https://github.com/stackblitz/webcontainer-core/issues/447

**Closed by jrvidal** 2022-02-09 10:47 UTC

**Comment by amalbenny** [comment] 2022-02-12 01:05
> Most likely a duplicate of #447

But im my case only the ' preview' is restricted. Others (edtor tab will work normally) are working well.
![Screenshot_2022-02-12-06-32-56-69_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/77718636/153689864-30ee1ad9-2971-45e0-84d9-8aa7c7ce60a6.jpg)
![Screenshot_2022-02-12-06-32-49-48_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/77718636/153689867-08f29596-24ea-4f1e-858e-7d6716d6f54a.jpg)

**Comment by jrvidal** [comment] 2022-02-13 21:05
Yep, that's expected. The editor itself is cross-browser, it's the underlying runtime that has platform support limitations. [Our documentation](https://developer.stackblitz.com/docs/platform/browser-support) has a little more detail about it.
