### ISSUE TITLE
Repo subfolder 404 error

### ISSUE THREAD

**Issue by CGiustiniani** [stackblitz/webcontainer-core#873] opened 2022-10-22 21:11 UTC
### Describe the bug

Subfolder of my repo containing a small angular app, returns 404 when opened via codeflow / pr.new
- It does work locally
- It does work using the stackblitz.com/github url scheme
- It does **not** work using pr.new & codeflow

### Link to the blitz that caused the error

https://pr.new/github.com/CGiustiniani/FrontendLearning/tree/main/angular/forms-and-validation/task

### Steps to reproduce

1. Go to https://github.com/CGiustiniani/FrontendLearning/tree/main/angular/forms-and-validation/task
2. modify the URL and add pr.new/ as described in the documentation
3. The link should look like this now 
https://pr.new/github.com/CGiustiniani/FrontendLearning/tree/main/angular/forms-and-validation/task
4. Codeflow tries to load the repo, but fails with 404 not found and removed the subfolder from the URL 

### Expected behavior

Codeflow should be able to find and import the angular application, similar to how stackblitz.com/github/ URL is able to import and open it.
URL: https://stackblitz.com/github/CGiustiniani/FrontendLearning/tree/main/angular/forms-and-validation/task

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

Codeflow (not working) using pr.new 

![image](https://user-images.githubusercontent.com/97685381/197362499-58c5c4a9-8126-4fcc-93b9-f1031ec6f939.png)

stackblitz.com/github/.... (working)

![image](https://user-images.githubusercontent.com/97685381/197362456-ba7a714a-a4e0-497a-befd-4aedc38e244e.png)

### Platform

```
Version = 1.67.0
Hash = 771d21865841b49ec9d3de318b49ea649c509949
WebContainer = dfae8564d35fe429a0bab219bd7d77341f3ec782

Browser name  = Chrome
Full version  = 106.0.0.0
Major version = 106
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 114006428,
  "usedJSHeapSize": 96871200,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by SamVerschueren** [comment] 2023-03-08 12:10
Closing as duplicate of #865.

**Closed by SamVerschueren** 2023-03-08 12:10 UTC
Labels: ui
