### ISSUE TITLE
Refreshing of web page causes infinite refresh loop when DevTools are open

### ISSUE THREAD

**Issue by danawoodman** [stackblitz/webcontainer-core#801] opened 2022-09-08 15:09 UTC
### Describe the bug

When i click the refresh icon in a container while devtools are open, the browser goes into an infinite refresh loop and has to be closed and reopened to work again. This makes debugging SSR stuff impossible.

### Link to the blitz that caused the error

https://stackblitz.com/edit/sveltejs-kit-template-default-ekuxpn

### Steps to reproduce

1. Open this container: https://stackblitz.com/edit/sveltejs-kit-template-default-ekuxpn
2. Reload the web view

### Expected behavior

Shouldnt reload constantly

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![Screen Recording 2022-09-08 at 08 08 15 AM](https://user-images.githubusercontent.com/157695/189158531-106db1c1-ac17-4805-9328-d4c509085886.gif)

### Platform

```
Browser name  = Chrome
Full version  = 104.0.0.0
Major version = 104
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 83434583,
  "usedJSHeapSize": 77696055,
  "jsHeapSizeLimit": 4294705152
}
Hash = a1e315a41ec6498e2c2758b32fbf437db67b244b
```

### Additional context

Tested in private browsing mode; same result

**Comment by d3lm** [comment] 2022-09-17 13:39
Hey there 👋 I can't reproduce this on my end. Do you maybe have the project open twice? You can't have the same project open in 2 or more tabs.

**Comment by danawoodman** [comment] 2022-09-19 18:00
Try this:

1. Open the web preview in a new tab
2. Open dev tools 
3. Reload the page 

GIF: https://a.cl.ly/P8u7mR6G

I just tried again and it did the same

**Comment by SamVerschueren** [comment] 2023-03-08 11:40
@danawoodman Is it possible you had `Update on Reload` turned on in `DevTools > Application > Service Workers`? We saw issues regarding this before.

Closing as duplicate of #690.

**Closed by SamVerschueren** 2023-03-08 11:40 UTC
