### ISSUE TITLE
Not able to create component in the terminal

### ISSUE THREAD

**Issue by priyaprao** [stackblitz/webcontainer-core#603] opened 2022-02-21 18:26 UTC
### Describe the bug

I was following through the steps to create a component (https://angular.io/start) by opening new terminal and it through an error:
~/projects/mr36pi--run
❯ ng generate component product-alerts 
An unhandled exception occurred: Cannot set property global of #<Object> which has only a getter
See "/tmp/ng-lYupLT/angular-errors.log" for further details.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.ts

### Steps to reproduce

Open new terminal in the project.
run "ng generate component product-alerts" 

### Expected behavior

Should generate a component

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 98.0.4758.80
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 96834451,
  "usedJSHeapSize": 92993967,
  "jsHeapSizeLimit": 4294705152
}
Hash = d64d45524a435df425e7813603b52872ecfbe08e
```

**Comment by jrvidal** [comment] 2022-02-22 15:16
Duplicate of https://github.com/stackblitz/webcontainer-core/issues/604

**Closed by jrvidal** 2022-02-22 15:16 UTC
