### ISSUE TITLE
Prisma can't generate in Codeflow

### ISSUE THREAD

**Issue by pegak** [stackblitz/webcontainer-core#954] opened 2023-01-31 22:49 UTC
### Describe the bug

Installation of dependencies fails when Prisma wants to generate the types. Error is:
```bash
prisma generate

prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
Please manually install OpenSSL and try installing Prisma again.
prisma:warn Prisma failed to detect the Linux distro in use, and may not work as expected. Defaulting to "debian".
> Downloading Prisma engines for Node-API for debian-openssl-1.1.x [                    ] 0%Error: request to https://binaries.prisma.sh/all_commits/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/debian-openssl-1.1.x/libquery_engine.so.node.gz.sha256 failed, reason: socket hang up

 ELIFECYCLE  Command failed with exit code 1.
```

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/pegak/nauc-me-it

### Steps to reproduce

1. Go to project
2. Run `pnpm i`
3. See the error

### Expected behavior

Correct installation and running app.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="967" alt="image" src="https://user-images.githubusercontent.com/12586960/215900009-9fdffc7e-e9ed-4d48-9062-cbb66a2820eb.png">

### Platform

```
Version = 1.72.0
Hash = 18daa5a75f7495f4d5eaa201699efea78f76ac4d
WebContainer = 522185bb0134fb732ed5ecb9887332d7f888ce1b

Browser name  = Edge
Full version  = 111.0.1653.0 (Official build) canary (64-bit)
Major version = 111
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.0.0
performance.memory = {
  "totalJSHeapSize": 117598380,
  "usedJSHeapSize": 92486660,
  "jsHeapSizeLimit": 4294705152
}
```
```
Version = 1.72.0
Hash = 18daa5a75f7495f4d5eaa201699efea78f76ac4d
WebContainer = 522185bb0134fb732ed5ecb9887332d7f888ce1b

Browser name  = Chrome
Full version  = 109.0.0.0
Major version = 109
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 69638458,
  "usedJSHeapSize": 66084630,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

It is broken also in Chrome stable (added to Platform).

**Comment by d3lm** [comment] 2023-02-02 17:37
Hey there! Prisma is not supported in WebContainer as is because browser's can't execute native binaries. For this to work the required native binaries need to be compiled to Wasm. I ll close this for now, cause there is not much we can do at this point.

**Closed by d3lm** 2023-02-02 17:37 UTC

**Comment by pegak** [comment] 2023-02-02 17:46
Hi,
thanks for reply. So maybe Xata would work? :)

**Comment by janpio** [comment] 2023-02-03 20:31
(I work at Prisma)

It is interesting to me that not running the engine fails (which would be expected for the reasons you mentioned - we are working on Wasm-ifying many of them where possible), but downloading with "socket hang up". Is that also a limitation of WebContainer or something else?

**Comment by d3lm** [comment] 2023-02-05 12:19
@pegak I have never used Xata, maybe you can give it a try and see if you run into issues.

**Comment by d3lm** [comment] 2023-02-05 12:33
@janpio That's wonderful news. It'd be really cool if most parts would be Wasm-ified and maybe that would allow folks to run Prisma in WebContainer. Regarding "socket hang up", that's due to CORS because https://binaries.prisma.sh is blocking requests from `*.staticblitz.com`. If you can enable CORS for that domain the socket shouldn't hang up anymore.

**Comment by janpio** [comment] 2023-02-11 19:44
I worked around the CORS issue, but as expected our engines still fail to start properly. 

The Node-API one with `Cannot load native addon because loading addons is disabled`, and the binary one with `a command can only contain words and redirects`: https://github.com/prisma/prisma/issues/17710#issuecomment-1426860232 As said, not surprising. Should I open issues for them anyway?

**Comment by janpio** [comment] 2023-02-23 10:27
I don't know how you do things around here, at Prisma I would want to have an issue to track the error message and be able to explain what is going on and why. I for example have no idea how that `can only contain words and redirects` error message makes sense here.

**Comment by d3lm** [comment] 2023-02-23 19:04
Yea, for that error with binaries we may wanna open an issue, but for loading native addons as that's working as intended. Wanna open an issue for the binary error message?
