### ISSUE TITLE
Stackblitz infinitly colones the respertory.

### ISSUE THREAD

**Issue by bcrhbrhcdb** [stackblitz/webcontainer-core#1351] opened 2024-02-28 18:30 UTC
### Describe the bug

![Screenshot 2024-02-28 12 28 44](https://github.com/stackblitz/webcontainer-core/assets/123518949/fa864fa3-255b-46b9-a322-cf9c0594495c)

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/bcrhbrhcdb/noob-cIicker

### Steps to reproduce

I do not know.

### Expected behavior

Stackblitz should connect to my respiratory. I tried adding files via github.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = cb3c5872d838650fa710504267727c89c0b45070
WebContainer = c9a8a620

Browser name  = Chrome
Full version  = 121.0.0.0
Major version = 121
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 114972473,
  "usedJSHeapSize": 105259853,
  "jsHeapSizeLimit": 2055208960
}
```

**Comment by coder0107git** [comment] 2024-02-29 01:57
It seems that you also reported this [here](https://github.com/stackblitz/core/issues/2990).

**Comment by Nemikolh** [comment] 2024-02-29 07:55
Closing as it is a duplicate of https://github.com/stackblitz/core/issues/2990 as pointed out by @coder0107git (Thanks! 👍)

**Closed** 2024-02-29 07:55 UTC
