### ISSUE TITLE
how to change registry of npm

### ISSUE THREAD

**Issue by abchexuzheng** [stackblitz/webcontainer-core#981] opened 2023-03-01 08:37 UTC
show we use private package in webcontainer

**Comment by SamVerschueren** [comment] 2023-03-02 10:22
Duplicate of #21. It's currently not yet possible. It's on our roadmap but I can't give an estimation on when it will be supported.

**Closed by SamVerschueren** 2023-03-02 10:22 UTC

**Comment by dxw0127** [comment] 2023-03-16 02:27
+1

**Comment by drfattytuna** [comment] 2023-04-04 15:32
+1

**Comment by SamVerschueren** [comment] 2025-04-11 12:45
@foreverzmy Please read the linked issue instead https://github.com/stackblitz/webcontainer-core/issues/21#issuecomment-1857842039
