### ISSUE TITLE
Multiple unexpected errors

### ISSUE THREAD

**Issue by DaniGuardiola** [stackblitz/webcontainer-core#1466] opened 2024-06-16 13:23 UTC
### Describe the bug

I'm getting errors like these:

```
Module '"stackblitz:/node_modules/@types/react/ts5.0/index"' can only be default-imported using the 'esModuleInterop' flag(1259)
```

```
Cannot use JSX unless the '--jsx' flag is provided.(17004)
```

However, these do not make sense since everything is set up correctly. I based this blitz on the built-in React TypeScript template and simply followed the steps [here](https://tailwindcss.com/docs/guides/vite) to add Tailwind CSS support to it.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-6pzzro?file=tailwind.config.js,src%2Fmain.tsx,src%2FApp.tsx,tsconfig.app.json&terminal=dev

### Steps to reproduce

1. Open sandbox.
2. See errors in `.ts` files.

### Expected behavior

There are no errors.

Note: I have not run this locally, because the [linked guide in the issue form](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) is completely unhelpful at guiding me to export the project so I can run it locally, I couldn't find the option in the UI, and I'm not about to recreate the file structure and manually copy the contents of each file. But since it's a required checkbox, I checked it rather than throwing this issue away.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="492" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/8862967/36e3f358-052f-4ae7-837a-78a8bb5af700">

<img width="772" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/8862967/d1d9b2cb-e354-4da8-93ad-3a6888a402fd">

<img width="545" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/8862967/b4a370d0-5826-449c-9a7f-56bc6071817a">

<img width="865" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/8862967/e48db576-fae9-4868-b11f-ec3a75fa2068">

### Platform

```
Browser name  = Chrome
Full version  = 125.0.0.0
Major version = 125
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 143114081,
  "usedJSHeapSize": 137272577,
  "jsHeapSizeLimit": 4294705152
}
Hash = 9e2d28a3
```

**Comment by NickWoodward** [comment] 2024-06-24 20:38
I'm literally getting this from the stackblitz React/TS starter template, incredibly annoying. Did you find a solution?

**Comment by namuol** [comment] 2024-07-03 23:16
Duplicate of #1465

**Comment by SamVerschueren** [comment] 2024-07-15 07:03
Closing in favour of #1465 

> We are aware of this issue and we have a fix for it. I will try to get it released today.

**Closed by SamVerschueren** 2024-07-15 07:03 UTC
