### ISSUE TITLE
Turbo can't resolve npm git versions

### ISSUE THREAD

**Issue by WilsontheWolf** [stackblitz/webcontainer-core#462] opened 2021-12-06 01:33 UTC
### Describe the bug

When using a git version of a dependancy turbo errors.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-m6bjnu?file=package.json

### Steps to reproduce

1. Load project
2. Wait to install
3. See error

### Expected behavior

It should clone this repo properly and install it.

### Platform

- OS: linux
- Browser: brave
- Version:93.0

### Additional context

Cloning this repo also provides the same issue if you need more info https://github.com/WilsontheWolf/repo

**Comment by d3lm** [comment] 2021-12-06 08:05
Hey, that's right. Turbo currently only supports dependencies published via npm. Supporting git is on our roadmap though. If there's progress on this we keep you posted here.

**Comment by SamVerschueren** [comment] 2023-02-22 09:58
Closing as duplicate of #99 where we track support for git dependencies.

**Closed by SamVerschueren** 2023-02-22 09:58 UTC
Labels: tracked
