### ISSUE TITLE
Not able to install typescript in node template (vite/vanilla-ts is also affected)

### ISSUE THREAD

**Issue by marcelschork** [stackblitz/webcontainer-core#422] opened 2021-11-22 14:25 UTC
### Describe the bug

Once I try to install typescript in the node environment the dependencies can't be fetched (see attached screenshot). The vite vanilla ts template is also affected. 

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-qmxwoc?file=package.json

### Steps to reproduce

1. Just open the blitz

### Expected behavior

Installation of typescript works

### Screenshots

![image](https://user-images.githubusercontent.com/63337737/142878039-faf6f7c6-cf58-421f-8f61-5da387d10bfe.png)

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.81
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 Edg/94.0.992.47
performance.memory = {
  "totalJSHeapSize": 88259846,
  "usedJSHeapSize": 84397778,
  "jsHeapSizeLimit": 4294705152
}
Hash = 5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b
```

**Comment by geromegrignon** [comment] 2021-11-22 14:34
Hey @marcelschork,

I can't reproduce it.
I succeeded in opening your link and by creating a new NodeJS WebContainer and installing it with `npm install typescript`.

**Comment by jrvidal** [comment] 2022-01-20 14:26
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.

**Closed by jrvidal** 2022-01-20 14:26 UTC
Labels: needs more info
