### ISSUE TITLE
Open in new tab is not working using Firefox

### ISSUE THREAD

**Issue by aminsaedi** [stackblitz/webcontainer-core#879] opened 2022-10-27 16:32 UTC
### Describe the bug

I clicked on "Open in new tab button" and in the newly opened tab it shoes "Unable to connect to local-corp.webcontainer.io".

I tried it in google chrome and it's working as expected without any issue

### Link to the blitz that caused the error

https://stackblitz.com/github/remix-run/react-router/tree/main/examples/modal?file=src%2FApp.tsx

### Steps to reproduce

1. click on open in new tab
2. it says 'Unable to connect to the project'

### Expected behavior

open the output in a new tab

### Parity with Local

- [ ] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Firefox
Full version  = 105.0
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0
performance.memory = undefined
Hash = 912cb019f8b62040b90085f00ac69aca69f51e29
```

**Comment by leochras** [comment] 2022-10-28 08:51
same, I only get this: 
![image](https://user-images.githubusercontent.com/16163571/198546494-8aa57774-dcfe-44ac-b9da-211de62d9304.png)

**Comment by edimitchel** [comment] 2023-02-23 13:48
It seams it's a duplicate

Duplicate of #811

**Comment by d3lm** [comment] 2023-02-23 19:03
Yep, this is related to storage partitioning which has been rolled out in Firefox but not Chrome yet. As mentioned in #811 we are working on a fix already. Thanks for reporting this issue. I am going to close this as we are tracking this in #811.

**Closed by d3lm** 2023-02-23 19:03 UTC
