### ISSUE TITLE
Process Timers Error

### ISSUE THREAD

**Issue by derekbar90** [stackblitz/webcontainer-core#598] opened 2022-02-21 04:15 UTC
### Describe the bug

When running a node js script that should be waiting for a child process to execute fails to process, fails. During the same execute cycle, other processes pass which makes me feel this could happen when executing multiple child processes. If resolved, an Ethereum development stack would be fully supported within Stackblitz, it currently is able to compile solidity but not test.

### Link to the blitz that caused the error

https://stackblitz.com/github/derekbar90/hardhat-boilerplate-typescript?file=package.json

### Steps to reproduce

npm install
npm run test

### Expected behavior

Should pass all tests. 

```
➜  hardhat-boilerplate-typescript git:(master) ✗ yarn test                           
yarn run v1.22.17
warning ../../../package.json: No license field
$ hardhat test
Compiling 33 files with 0.8.10
Generating typings for: 33 artifacts in dir: ./types for target: ethers-v5
Successfully generated 47 typings!
Solidity compilation finished successfully


  Random Token
    ✓ Should create and mint total supply
    ✓ Should create snapshot (82ms)
    ✓ Should have different snapshots when taken twice (156ms)
    ✓ Should not create snapshot when sender lacks admin role
    ✓ Should add allowance via permit (242ms)


  5 passing (4s)

✨  Done in 16.45s.
```

### Parity with Local

- [X] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 98.0.4758.102
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 132370676,
  "usedJSHeapSize": 124267408,
  "jsHeapSizeLimit": 4294705152
}
Hash = e1937cc6e2ee7e7a1da198d43493f4063378a564
```

### Additional context

```
"before all" hook for "Should create and mint total supply":
     Error: Timeout of 40000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/projects/bnmipwyjg.github/test/01_random_token.ts)
      at listOnTimeout (https://bnmipwyjg--github.w.staticblitz.com/blitz.e1937cc6e2ee7e7a1da198d43493f4063378a564.js:6:272931)
      at processTimers (https://bnmipwyjg--github.w.staticblitz.com/blitz.e1937cc6e2ee7e7a1da198d43493f4063378a564.js:6:273745)
      at https://bnmipwyjg--github.w.staticblitz.com/blitz.e1937cc6e2ee7e7a1da198d43493f4063378a564.js:15:141537
      at https://bnmipwyjg--github.w.staticblitz.com/blitz.e1937cc6e2ee7e7a1da198d43493f4063378a564.js:15:141845
```

**Comment by d3lm** [comment] 2022-04-04 18:19
Hey there! Sorry for the late response.

The project doesn't seem to exist anymore. Do you have link for us?

Also it would be very helpful if you had a minimal reproduction for us.

**Comment by derekbar90** [comment] 2022-04-06 18:32
@d3lm Hey sorry about this, I had committed some stuff by accident and needed to bring it private. I've changed the visibility back to public. You should be able to reproduce now. Sorry about that! Thank you in advance for your time looking into this.

**Comment by derekbar90** [comment] 2022-04-06 18:32
@jrvidal I think we can remove this label now. Thank you for adding it in the meantime.

**Comment by alcuadrado** [comment] 2023-03-15 14:59
We use that native addon now, and are planning to use more in the future.

If there's an easy way to fallback to wasm, we'll do. We use NAPI-rs, [which plans to make it easy](https://github.com/napi-rs/napi-rs/issues/1493).

**Comment by d3lm** [comment] 2023-03-20 10:31
Yep that is right. They are planning Wasm support. I am going to close this issue for now because there is not much we can do about native addons on our end. If you run into the timer issue again though, please feel free to file a new report. Would love to see an Ethereum development stack running in WebContainer 🙌

**Closed by d3lm** 2023-03-20 10:31 UTC
Labels: needs more info
