### ISSUE TITLE
Project not running

### ISSUE THREAD

**Issue by apacurariu** [stackblitz/webcontainer-core#387] opened 2021-11-07 13:22 UTC
### Describe the bug

The project is not running - the web container remains stuck at "Running start command" despite the terminal showing a complete successful build and indicates that the server is running "** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **"

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fbadge-overview-example.html

### Steps to reproduce

Try running the badge overview example here - https://material.angular.io/components/badge/examples

### Expected behavior

The project should run

### Screenshots

![image](https://user-images.githubusercontent.com/9416237/140646783-cfb1bc2d-4d8e-423e-abc5-22bb53841693.png)

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 101561949,
  "usedJSHeapSize": 94969113,
  "jsHeapSizeLimit": 4294705152
}
Hash = d83b9b15484f32317787d8c7cc41da5651102bdc
```

**Comment by d3lm** [comment] 2021-11-07 17:26
Hey there! I cannot reproduce this issue, it works fine for me.

![image](https://user-images.githubusercontent.com/12571019/140655158-03394c72-fe8a-4da3-ab26-6171c9f98abb.png)

What about you @jrvidal @SamVerschueren?

**Comment by SamVerschueren** [comment] 2021-11-08 08:04
Seems to work on my end as well. @apacurariu can you test again and see if this issue still occurs?

**Comment by apacurariu-appical** [comment] 2021-11-08 09:23
Hi @SamVerschueren and @d3lm - thanks for the quick response! I will try again and will update you both.

**Comment by apacurariu** [comment] 2021-11-08 09:25
Hi @SamVerschueren and @d3lm - thank you both for the quick response. I'll try again and will update you both.

**Comment by apacurariu** [comment] 2021-11-09 08:16
Update: It works great on Edge (takes around a minute or so to compile on load). On Chrome I waited way over 5 minutes and it's stuck on "Running start command" as shown in my previous attachment.  At first I assume that it could be my machine running low on RAM but then I tried Edge and it worked. Maybe important - I disabled 3rd party cookies on Chrome, could that have an impact?

Cheers,
Andrei

**Comment by jrvidal** [comment] 2021-11-09 09:02
> I disabled 3rd party cookies on Chrome, could that have an impact?

Yes, that will definitely have an impact. You can check your devtools console and should see errors regarding service workers not being able to register. We need to improve the UX around this failure mode, but in the meantime, you can enable 3rd party cookies manually and those errors should go away.

**Comment by apacurariu** [comment] 2021-11-09 11:55
Thank you for the quick response. Shall I close this or keep it open?

**Comment by d3lm** [comment] 2021-11-09 14:24
I think we can close this issue now. If you run into any more issues @apacurariu feel free to open a new issue.

**Closed by d3lm** 2021-11-09 14:24 UTC
Labels: needs more info
