### ISSUE TITLE
Error: Could not resolve reference "refs/heads/master".

### ISSUE THREAD

**Issue by utsavberi** [stackblitz/webcontainer-core#263] opened 2021-07-25 21:30 UTC
### Describe the bug

Get a `Error: Could not resolve reference "refs/heads/master".` error while importing from an existing github repo which has main instead of master as the root branch

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-43jpyj

### Steps to reproduce

1. Go to `Connect to Github`
2. Import from existing
3. add repo url https://github.com/utsavberi/LevelUpFitness-Web

### Expected behavior

Expected to see repo files but saw the above error message and an infinite spinner on the branch name box (top left)

### Platform

```
Browser name  = Chrome 
Full version  = 90.0.4430.93
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 54858874,
  "usedJSHeapSize": 46652302,
  "jsHeapSizeLimit": 4294705152
}
Hash = d86858d537c0a310ebafd72a06454769861ab23a
```

**Comment by tony19** [comment] 2021-07-25 22:50
This is a duplicate of #195

**Comment by jrvidal** [comment] 2022-03-14 13:54
Duplicate of #195

**Closed by jrvidal** 2022-03-14 13:54 UTC
