### ISSUE TITLE
BUG: Unable to install package

### ISSUE THREAD

**Issue by JANSON-JOHN** [stackblitz/webcontainer-core#127] opened 2021-05-31 05:47 UTC
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-fgkfyg?file=index.js

**Steps to reproduce:**

1. Go to 'Terminal...'
2. Run  ' npm i -g editly   '
3. Scroll down 

**Expected behavior:**

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 49887371,
  "usedJSHeapSize": 46572295,
  "jsHeapSizeLimit": 820248576
}

**Additional context:**

**Comment by SamVerschueren** [comment] 2021-05-31 06:40
Hi @JANSON-JOHN! Thanks for trying out WebContainers 🙏 !

We currently don't support installing npm packages as global. The reason for this is a little nuanced. What does global even mean in the context of stackblitz. Would you want it to be available in all of your blitz's? What about collisions in that case where you install a global version which collides with a local dependency.

It's considered a bad practice to install global packages so we might never support it. To get your use case to work, please install the dep as a `devDependency` and use npx `${commandName}` to run the command. This will look up the binary in the `node_modules/.bin` folder. 

Currently we also just support `npm install editly` and then run `editly` from the command line directly. However, I noticed that `editly` uses native binaries (ffmpeg) which does not work in the browser unless you use some WASM replacement for ffmpeg.

Closing this as it works as intended.

**Closed by SamVerschueren** 2021-05-31 06:40 UTC

**Comment by JANSON-JOHN** [comment] 2021-05-31 09:45
Hi Sam,

Thanks a lot for the quick reply. Usually reply times are very high. Sorry
for filing the issue.

Happy to get advice and installed as
npm install editly --save-dev

**Comment by SamVerschueren** [comment] 2021-05-31 10:52
No worries, feel free to open new issues in the future if you run into other things 😃 !
