### ISSUE TITLE
Vitest reporter pane is blank

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#536] opened 2022-01-14 21:48 UTC
### Describe the bug

The Vitest reporter pane [shown in the tweet](https://twitter.com/i/status/1481717677139935241) is just blank when I open https://vitest.new:

![vitest-pane-blank](https://user-images.githubusercontent.com/26580/149589546-e5a8e67e-006b-4387-a625-21755fe85e66.gif)

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitest-dev-vitest-squjqn?file=test%2Fbasic.test.ts

### Steps to reproduce

1. Open https://vitest.new
2. Observe the Vitest reporter pane is blank.
3. Observe two extra split panes to the right of the Vitest reporter pane that are also blank.

### Expected behavior

* The Vitest reporter pane shows the test results.
* No extra blank panes that serve no purpose.

### Parity with Local

- [x] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

<img width="1280" alt="Screen Shot 2022-01-14 at 3 33 11 PM" src="https://user-images.githubusercontent.com/26580/149588526-da7f2808-4af5-4466-9747-ca943141e822.png">

### Platform

```
Browser name  = Chrome 
Full version  = 97.0.4692.71
Major version = 97
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 70690193,
  "usedJSHeapSize": 65429597,
  "jsHeapSizeLimit": 4294705152
}
Hash = d4ed89204e54de5c40d109298317e6dc4d60aef7
```

### Additional context

Console log:

```
.localservice@runtim…17e6dc4d60aef7.js:7 Uncaught 
_0x4cc0ec {code: 1002, message: 'RSV2 and RSV3 must be clear'}
code: 1002
message: "RSV2 and RSV3 must be clear"
[[Prototype]]: Object
```
```
vitest-dev-vitest-4e….webcontainer.io/:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at parse (<anonymous>)
    at bM (vitest-dev-vitest-4edn2l--51204.local.webcontainer.io/__vitest__/assets/vendor.1560970a.js:8:23751)
    at vitest-dev-vitest-4edn2l--51204.local.webcontainer.io/__vitest__/assets/vendor.1560970a.js:8:22534
    at _0x263926.<anonymous> (vitest-dev-vitest-4edn2l--51204.local.webcontainer.io/__vitest__/assets/index.8d7a5168.js:1:3504)
    at _0x263926.dispatchEvent (.localservice@runtime.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:1:28929)
    at _0x263926._handleMessage (.localservice@runtime.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:7:18258)
    at MessagePort._0x49f884 (.localservice@runtime.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:7:14830)
````

**Comment by tony19** [comment] 2022-01-14 21:55
Oddly, it works now in a new tab.

**Comment by jrvidal** [comment] 2022-01-24 10:57
@tony19 Thanks for the report.

> * [ ]  I have run the project in my local machine and I could not reproduce the issue.

Can you confirm whether you ran this project locally and it worked?

> .localservice@runtim…17e6dc4d60aef7.js:7 Uncaught 
_0x4cc0ec {code: 1002, message: 'RSV2 and RSV3 must be clear'}
code: 1002
message: "RSV2 and RSV3 must be clear"
[[Prototype]]: Object

FWIW we just deployed a fix for this issue.

**Comment by tony19** [comment] 2022-01-24 13:45
Yes, this works locally, as it does currently in new instances of vite.new in StackBlitz.

**Comment by jrvidal** [comment] 2022-01-24 13:52
I can't reproduce on the original blitz anymore. Are you still seeing it?

**Comment by tony19** [comment] 2022-01-25 01:19
I think the original issue is resolved, so feel free to close 🎉 !

---

FYI, there seems to be a Vitest UI bug that affects https://vitest.new, where it crashes at startup, and prevents the preview pane from rendering at all:

<img width="936" alt="Screen Shot 2022-01-24 at 6 50 55 PM" src="https://user-images.githubusercontent.com/26580/150889913-33803a5c-4791-434e-bbdc-2bd2d871f461.png">

I'll report it in `@vitest/ui`, and link the issue here when I can.

**Comment by jrvidal** [comment] 2022-01-25 07:55
Interesting, we'll keep an eye on that as well. Thanks!

**Closed by jrvidal** 2022-01-25 07:55 UTC
Labels: needs more info
