### ISSUE TITLE
BUG: Next.js navigation didn't change the browser path

### ISSUE THREAD

**Issue by lfades** [stackblitz/webcontainer-core#108] opened 2021-05-27 21:24 UTC
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/github/vercel/next.js/tree/canary/examples/hello-world?file=pages%2Findex.js

**Steps to reproduce:**

Load the blitz, once you see the browser rendering "Hello world. _About_", click on about and it takes you to the about page (`/about`), but that should be updating the path too, like how it happens when you open the app in another tab.

**Expected behavior:**

The path should be changing after a Next.js navigation

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64429086,
  "usedJSHeapSize": 59433006,
  "jsHeapSizeLimit": 4294705152
}

**Additional context**

Maybe this behavior is intended? I'm not sure but it didn't feel normal to me

**Comment by SamVerschueren** [comment] 2021-05-29 05:40
Thanks for reporting this @lfades! We are aware of this behaviour and we have it planned but can't give you a timeframe.

**Comment by SamVerschueren** [comment] 2023-03-10 07:58
Duplicate of #611

**Closed by SamVerschueren** 2023-03-10 07:58 UTC
Labels: tracked
