### ISSUE TITLE
BUG: npx reinstalls existing packages

### ISSUE THREAD

**Issue by alcuadrado** [stackblitz/webcontainer-core#67] opened 2021-05-23 00:35 UTC
**Describe the bug**

I tried creating a new project, installing `hardhat` with `npm`, and running it with `npx`. It reinstalls `hardhat` every time I run it.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-2sxg1f?file=contracts%2Fc.sol

**To Reproduce**
1. Install hardhat with `npm i hardhat`
2. Run `npx hardhat`

**Expected behavior**
The local installation of `hardhat` should be run

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**
![image](https://user-images.githubusercontent.com/176499/119244306-a75d9e00-bb45-11eb-9919-2ba68a9fa2c3.png)

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 63265575,
  usedJSHeapSize: 61066615,
  jsHeapSizeLimit: 4294705152
}

**Comment by KwintenP** [comment] 2021-05-25 08:39
Hi!

🙏 for reporting. This does seem like a bug on our end!

**Comment by KwintenP** [comment] 2021-05-25 10:06
Closed as duplicate of #3

**Closed by KwintenP** 2021-05-25 10:06 UTC
Labels: bug, turbo
