### ISSUE TITLE
StackBlitz server crashed

### ISSUE THREAD

**Issue by reart93** [stackblitz/webcontainer-core#1469] opened 2024-06-23 12:23 UTC
### Describe the bug

.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/reart93/react_crud

### Steps to reproduce

.

### Expected behavior

.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = 499be3932f50ab06349575b1c9042f95bc072a8b
WebContainer = dc4d7514

Browser name  = Chrome
Full version  = 103.0.0.0
Major version = 103
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14816.131.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 111583947,
  "usedJSHeapSize": 98177451,
  "jsHeapSizeLimit": 2062548992
}
```

### Additional context

TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at registerModule (https://reactcrud-pxbj.w-credentialless-staticblitz.com/builtins.5bf3667c.js:161:1216)
    at registerImportModuleDynamically (https://reactcrud-pxbj.w-credentialless-staticblitz.com/builtins.5bf3667c.js:266:529)
    at internalCompileFunction (https://reactcrud-pxbj.w-credentialless-staticblitz.com/builtins.5bf3667c.js:266:1091)
    at wrapSafe (https://reactcrud-pxbj.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:13497)
    at Module._compile (https://reactcrud-pxbj.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:13881)
    at Module._extensions..js (https://reactcrud-pxbj.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:14855)
    at Module.load (https://reactcrud-pxbj.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:12820)
    at Module._load (https://reactcrud-pxbj.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:10273)
    at Function.executeUserEntryPoint [as runMain] (https://reactcrud-pxbj.w-credentialless-staticblitz.com/builtins.5bf3667c.js:165:1641)

Node.js 18.20.3

**Comment by kirjavascript** [comment] 2024-07-02 10:44
Hi :wave: thanks for the report!

This github project appears to be empty. What command are you running to get that error?

**Comment by kirjavascript** [comment] 2024-08-01 18:50
This bug has been reproduced, we are tracking it internally and will update here when it's fixed!

**Comment by SamVerschueren** [comment] 2024-08-07 10:39
Duplicate of https://github.com/stackblitz/webcontainer-core/issues/1492

This is now resolved.

**Closed by SamVerschueren** 2024-08-07 10:39 UTC
Labels: tracked
