### ISSUE TITLE
[BUG] Reload after changing code doesn't work

### ISSUE THREAD

**Issue by jifakir** [stackblitz/webcontainer-core#311] opened 2021-08-29 18:04 UTC
### Describe the bug

Unable to connect to local.webcontainer.io
No server listening on port 5000. Try:

Opening wrtc-socket on StackBlitz
Starting a server from the terminal with npm start
Open Project
Reload
![image](https://user-images.githubusercontent.com/67035363/131260656-4ccbbb0d-8e7a-4611-9eda-731a805d9b1a.png)

### Link to the blitz that caused the error

https://stackblitz.com/edit/wrtc-socket

### Steps to reproduce

=> Start the server.
=> Then change code or add something new.
=> Then try to reload
=> The webcontainer doesn't reloading properly.

### Expected behavior

It should reload properly after changing or adding code. Since I am using nodemon.

### Screenshots

![image](https://user-images.githubusercontent.com/67035363/131260609-b04b51f8-5b2f-4d42-b567-1a4e2d08d9e4.png)
I have added code but it isn't reloading properly. Instead shows an error.

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.159
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 77583719,
  "usedJSHeapSize": 73536935,
  "jsHeapSizeLimit": 2112094208
}
Hash = 8ffc536d8181e8b30c228dec423d18afae547c40
```

**Comment by d3lm** [comment] 2021-09-11 14:00
Thanks for reporting this issue and it appears to be a bug with our server implementation.

**Comment by jrvidal** [comment] 2021-09-14 11:51
@jifakir I cannot reproduce your issue. We recently merged a fix for a server bug that might be what you were observing. Please feel free to file again if you find any further issues. Thanks!

**Closed by jrvidal** 2021-09-14 11:51 UTC
Labels: bug, tracked
