### ISSUE TITLE
BUG: UI5 tooling is not working to develop and run OpenUI5 apps

### ISSUE THREAD

**Issue by marcelschork** [stackblitz/webcontainer-core#101] opened 2021-05-27 05:58 UTC
**Describe the bug**
Tried to run the [OpenUI5 sample app](https://github.com/SAP/openui5-sample-app) but the [UI5 tooling](https://sap.github.io/ui5-tooling/) is not working. It might be the missing `shrinkwrap.json` support which causes the issue.

**Link to the blitz that caused the error**
https://stackblitz.com/github/SAP/openui5-sample-app

**To Reproduce**
1. npm start

**Expected behavior**
Starting the dev server from the ui5 tooling 

**Screenshots**
<img width="769" alt="Screenshot 2021-05-27 at 07 45 11" src="https://user-images.githubusercontent.com/63337737/119773452-f0ed1680-bec0-11eb-878d-5d42bc67e6a9.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 90.0

**Comment by KwintenP** [comment] 2021-05-27 07:17
Hi!

Thanks for reporting 🙏 

Seems like the same issue as #91 . Gonna close this one as duplicate but I'll we'll take a look at your blitz as soon as the issue is fixed to verify.

**Comment by SamVerschueren** [comment] 2021-05-27 11:08
Reopening as this one is not fixed with fixing the root cause of #91. Looking into it right now.

**Comment by SamVerschueren** [comment] 2021-05-28 09:20
This is related to #53. The `ui5` package uses `getFileName()` under the hood which fails at the moment. Working on this so I'll keep you posted.

**Comment by SamVerschueren** [comment] 2021-06-02 06:19
@marcelschork we fixed some things and this seems to be working right now 🎉 ! Thanks for reporting the issue.

**Closed by SamVerschueren** 2021-06-02 06:19 UTC
Labels: bug
