### ISSUE TITLE
Using node-fetch custom headers ends with a socket hang up error

### ISSUE THREAD

**Issue by makma** [stackblitz/webcontainer-core#358] opened 2021-10-21 16:47 UTC
### Describe the bug

When using some API eg (`https://agify.io/`) with non-standard (at least that's my observation) HTTP headers there is an error in the Stackblitz console.

I came across this when I was trying to use SDK that internally uses an `Auth-token` header and I managed to create minimal steps to reproduce. 
On the local node environment (outside the WebContainer) this works just fine.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-22vjnb

### Steps to reproduce

1. Go to `https://stackblitz.com/edit/node-22vjnb`
2. run `node index.js`

Result: Error
```
This second request with a non standard header is not working
Error: request to https://api.agify.io/?name=bella failed, reason: socket hang up
    at async ModuleJob.run (https://node-22vjnb.jw.staticblitz.com/blitz.88a7151d177878d00bf438b30e057ed5805fdcd2.js:6:738889)
    at async Loader.import (https://node-22vjnb.jw.staticblitz.com/blitz.88a7151d177878d00bf438b30e057ed5805fdcd2.js:6:870264)
    at async Object.r.loadESM (https://node-22vjnb.jw.staticblitz.com/blitz.88a7151d177878d00bf438b30e057ed5805fdcd2.js:6:249893) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: undefined
}
```

### Expected behavior

Logged two JSON responses

### Screenshots

![image](https://user-images.githubusercontent.com/10922372/138321782-0dd98dea-79b4-4288-892c-adc9f9ee6be2.png)

### Platform

- OS: Windows 10
- Browser: Chrome,
- Version: Version 95.0.4638.54 (Official Build) (64-bit)

### Additional context

**Comment by d3lm** [comment] 2021-10-21 17:06
Hey there! This is unfortunately not a bug on our side. The reason the second call fails is due to CORS restrictions on that API you're trying to reach. Your second request contains a custom header which means it would send a preflight request first and that one gets blocked by CORS. The first one works, because you don't have a so called special request and there is no preflight request. Seems that the API does not allow that header:
```
Access-Control-Allow-Headers: Content-Type, X-Genderize-Source
```
Closing this issue. You could try and use a Chrome extension to work around the CORS issue.

**Closed as completed by d3lm** 2021-10-21 17:06 UTC
