### ISSUE TITLE
app won't start - any trick to this?

### ISSUE THREAD

**Issue by tysonrm** [stackblitz/webcontainer-core#245] opened 2021-07-15 08:47 UTC
**Describe the bug:**
<!- my app won't start. -->

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-3yzrsi

**Steps to reproduce:**

Install the app from github (beta feature)
http://github.com/module-federation/microlib
yarn build
yarn start

or use npm

https://stackblitz.com/edit/node-3yzrsi

❯ npm start
$ node --title aegis -r dotenv/config dist/index.js
Error: Cannot find module '/home/projects/node-3yzrsi/aegis'
    at Function.Module._resolveFilename (https://node-3yzrsi.jw.staticblitz.com/blitz.ded7c1cfbe6b33641b5f3c9265989f8bd71ed771.js:6:186558)
    at Function.Module._load (https://node-3yzrsi.jw.staticblitz.com/blitz.ded7c1cfbe6b33641b5f3c9265989f8bd71ed771.js:6:184175)
    at Function.executeUserEntryPoint [as runMain] (https://node-3yzrsi.jw.staticblitz.com/blitz.ded7c1cfbe6b33641b5f3c9265989f8bd71ed771.js:6:709049)
    at Object.a0_0x400c (https://node-3yzrsi.jw.staticblitz.com/blitz.ded7c1cfbe6b33641b5f3c9265989f8bd71ed771.js:6:1132061)
    at _0x4d4074 (https://node-3yzrsi.jw.staticblitz.com/blitz.ded7c1cfbe6b33641b5f3c9265989f8bd71ed771.js:8:23960)
    at _0x40da69 (https://node-3yzrsi.jw.staticblitz.com/blitz.ded7c1cfbe6b33641b5f3c9265989f8bd71ed771.js:11:42003)
    at _0x55cdb1 (https://node-3yzrsi.jw.staticblitz.com/blitz.ded7c1cfbe6b33641b5f3c9265989f8bd71ed771.js:11:262912)
    at Object.run (https://node-3yzrsi.jw.staticblitz.com/blitz.ded7c1cfbe6b33641b5f3c9265989f8bd71ed771.js:11:262050) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

~/projects/node-3yzrsi
❯ 

**Expected behavior:**

**Version of webcontainer:**
Hash: ded7c1cfbe6b33641b5f3c9265989f8bd71ed771

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.114
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 190737743,
  "usedJSHeapSize": 183237791,
  "jsHeapSizeLimit": 2172649472
}
```

**Additional context:**

**Comment by SamVerschueren** [comment] 2021-07-15 15:41
Hi @tysonrm! Thanks for trying StackBlitz out and reporting back. I believe this could have something to do with the `-r` flag which if I'm not mistaken, is currently not supported. But chiming in @d3lm for this. Not sure if this is the root cause but that's the first thing that caught my eye.

**Comment by d3lm** [comment] 2021-07-15 15:48
Yep that's correct. Currently, the `-r` is not yet supported but that's coming with what I am working on. So basically it won't pre-require your dotenv stuff right now. For the time being you could have one entry point which requires that and then requires the actual main module which you are trying to run. Try and see if that solves the issue or if you run into more issues.

**Comment by tysonrm** [comment] 2021-07-15 19:39
Sure, meant to fix that anyway. Good to know. Note that when i do remove -r as well as --title I run into...  

~/projects/node-3yzrsi 6s
❯ yarn start
$ node dist/index.js
TypeError: a is not a function
    at https://node-3yzrsi.jw.staticblitz.com/blitz.e6adaf772b18819f7b4ab8325b73d63276acda8f.js:6:224928
    at https://node-3yzrsi.jw.staticblitz.com/blitz.e6adaf772b18819f7b4ab8325b73d63276acda8f.js:6:34189
    at Object.eval (/home/projects/node-3yzrsi/node_modules/jose/lib/registry/ec_curves.js:5:5)
    at Object.function (https://node-3yzrsi.jw.staticblitz.com/blitz.e6adaf772b18819f7b4ab8325b73d63276acda8f.js:11:169884)
    at Module._compile (https://node-3yzrsi.jw.staticblitz.com/blitz.e6adaf772b18819f7b4ab8325b73d63276acda8f.js:6:188591)
    at Object.Module._extensions..js (https://node-3yzrsi.jw.staticblitz.com/blitz.e6adaf772b18819f7b4ab8325b73d63276acda8f.js:6:188950)
    at Module.load (https://node-3yzrsi.jw.staticblitz.com/blitz.e6adaf772b18819f7b4ab8325b73d63276acda8f.js:6:187030)
    at Function.Module._load (https://node-3yzrsi.jw.staticblitz.com/blitz.e6adaf772b18819f7b4ab8325b73d63276acda8f.js:6:184608)
    at Module.require (https://node-3yzrsi.jw.staticblitz.com/blitz.e6adaf772b18819f7b4ab8325b73d63276acda8f.js:6:187346)
    at i (https://node-3yzrsi.jw.staticblitz.com/blitz.e6adaf772b18819f7b4ab8325b73d63276acda8f.js:6:425983)


BTW, this thing is awesome. Hope to get up and running soon. THanks!

**Comment by tysonrm** [comment] 2021-07-16 05:09
this is the same problem mentioned here https://github.com/stackblitz/webcontainer-core/issues/140

**Comment by d3lm** [comment] 2021-09-24 22:25
Quick update, the `-r` flag is now supported.

Yea, the `a is not a function` error seems to be crypto related. We will let you know when there's an update.

**Comment by jrvidal** [comment] 2022-01-20 22:54
@tysonrm We shipped a small fix for crypto that unblocked this. I now observe:
```
Error: Cannot find module '@module-federation/aegis'
```
both locally and on WebContainer, so I guess that we've achieved feature parity :wink: 

Do you want to try to fix this issue and submit a new blitz?

**Comment by tysonrm** [comment] 2022-01-21 04:19
I certainly will. Nice work. Thanks!

**Comment by kc0tlh** [comment] 2022-04-22 14:33
As it appears we've achieved feature parity with local I'm going to close this issue for now, but of course feel free to re-open if it pops back up for you!

**Closed by kc0tlh** 2022-04-22 14:33 UTC
Labels: needs more info
