### ISSUE TITLE
Cannot load project

### ISSUE THREAD

**Issue by pauloortizcuenca** [stackblitz/webcontainer-core#1255] opened 2023-11-21 06:57 UTC
### Describe the bug

Cannot load project. It keeps on loading 'Booting WebContainer'

![image](https://github.com/stackblitz/webcontainer-core/assets/50629973/cf42cc70-b925-48da-aa72-74ec2407f369)

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/pauloortizcuenca/Solo-Parents-MS

### Steps to reproduce

Dashboard then select github project

### Expected behavior

Load the project

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = 4f3918d67b0d0d6d912f5928adca1fb73bf3c67b
WebContainer = 9e24d36e

Browser name  = Chrome
Full version  = 119.0.0.0
Major version = 119
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 54505296,
  "usedJSHeapSize": 51807720,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by Nemikolh** [comment] 2023-11-21 10:13
Hey @pauloortizcuenca and @motss ! It seems that we have issues with our git integration. We have a fix that should be deployed soon.

I'll keep you posted.

**Comment by motss** [comment] 2023-11-21 10:15
Thanks @Nemikolh for the quick fix. Really appreciate that. 👍

**Comment by Nemikolh** [comment] 2023-11-21 10:18
Looks like the issue is fixed. I'll close this issue, feel free to open a new one if you run into any issues!

**Closed by Nemikolh** 2023-11-21 10:18 UTC
